In [1]:
from pathlib import Path
import os

from IPython.display import display
from pathlib import Path
from rasterio import features
import os
import pandas as pd
from satellites.shared.constants import SEED_NUMBER
from satellites.shared.notebook import configure_notebook
configure_notebook(seed=42, tensorflow=True)
import satellites.shared.io as io_l

from satellites.ml_classification import (
    GeospatialClassificationPipeline,
    ClassificationPipelineConfig,
)

In [2]:
WORK_PATH = Path("C:/work_dir/neuro_2024-2025a")

PARCELS_PATH = WORK_PATH / "1_eo_parcel_stats_fill" / "satellite_parcel_time_stats.geoparquet"
EDA_REPORT_PATH = WORK_PATH / "2_eo_results_eda_fill" / "eda_annotated_data.parquet"
PROPOSED_FEATURES_PATH = WORK_PATH / "2_eo_results_eda_fill" / "tables" / "feature_selection" / "feature_selection_proposal.csv"
OUTPUT_PATH = WORK_PATH / "3_eo_ml_classification_fill"

class_column = "crop_category"
parcel_id_column = "parcel_id"

In [3]:
gdf_parcels = io_l.read_data(str(PARCELS_PATH))
eda_parcels = io_l.read_data(str(EDA_REPORT_PATH))
eda_parcels = eda_parcels[[parcel_id_column, "is_outlier_97_5pct"]]
gdf_parcels = gdf_parcels.merge(eda_parcels, on=parcel_id_column, how="left")
gdf_parcels.head(3)

Reading file: C:/work_dir/neuro_2024-2025a/1_eo_parcel_stats_fill/satellite_parcel_time_stats.geoparquet
Reading file: C:/work_dir/neuro_2024-2025a/2_eo_results_eda_fill/eda_annotated_data.parquet

,parcel_id,crop_category,cluster,geometry,batch_number,intersected_pixel_count,meets_minimum_pixel_count,expected_pixel_count,observed_count,temporal_filled_pixel_count,spatial_filled_pixel_count,temporal_filled_ratio,spatial_filled_ratio,data_reliability_score,pixel_area,geom_area,geom_interior_area_ratio,geom_compactness,geom_perimeter_area_ratio,geom_shape_index,geom_elongation,geom_shape_complexity_score,B02_coefficient_of_variation__20241001,B02_coefficient_of_variation__20241101,B02_coefficient_of_variation__20241201,B02_coefficient_of_variation__20250101,B02_coefficient_of_variation__20250201,B02_coefficient_of_variation__20250301,B02_coefficient_of_variation__20250401,B02_coefficient_of_variation__20250501,B02_coefficient_of_variation__20250601,B02_coefficient_of_variation__20250701,B02_coefficient_of_variation__20250801,B02_coefficient_of_variation__20250901,B02_max__20241001,B02_max__20241101,B02_max__20241201,B02_max__20250101,B02_max__20250201,B02_max__20250301,B02_max__20250401,B02_max__20250501,B02_max__20250601,B02_max__20250701,B02_max__20250801,B02_max__20250901,B02_mean__20241001,B02_mean__20241101,B02_mean__20241201,B02_mean__20250101,B02_mean__20250201,B02_mean__20250301,B02_mean__20250401,B02_mean__20250501,B02_mean__20250601,B02_mean__20250701,B02_mean__20250801,B02_mean__20250901,B02_median__20241001,B02_median__20241101,B02_median__20241201,B02_median__20250101,B02_median__20250201,B02_median__20250301,B02_median__20250401,B02_median__20250501,B02_median__20250601,B02_median__20250701,B02_median__20250801,B02_median__20250901,B02_min__20241001,B02_min__20241101,B02_min__20241201,B02_min__20250101,B02_min__20250201,B02_min__20250301,B02_min__20250401,B02_min__20250501,B02_min__20250601,B02_min__20250701,B02_min__20250801,B02_min__20250901,B02_range__20241001,B02_range__20241101,B02_range__20241201,B02_range__20250101,B02_range__20250201,B02_range__20250301,B02_range__20250401,B02_range__20250501,B02_range__20250601,B02_range__20250701,B02_range__20250801,B02_range__20250901,B02_sd__20241001,B02_sd__20241101,B02_sd__20241201,B02_sd__20250101,B02_sd__20250201,B02_sd__20250301,B02_sd__20250401,B02_sd__20250501,B02_sd__20250601,B02_sd__20250701,B02_sd__20250801,B02_sd__20250901,B02_variance__20241001,B02_variance__20241101,B02_variance__20241201,B02_variance__20250101,B02_variance__20250201,B02_variance__20250301,B02_variance__20250401,B02_variance__20250501,B02_variance__20250601,B02_variance__20250701,B02_variance__20250801,B02_variance__20250901,B03_coefficient_of_variation__20241001,B03_coefficient_of_variation__20241101,B03_coefficient_of_variation__20241201,B03_coefficient_of_variation__20250101,B03_coefficient_of_variation__20250201,B03_coefficient_of_variation__20250301,B03_coefficient_of_variation__20250401,B03_coefficient_of_variation__20250501,B03_coefficient_of_variation__20250601,B03_coefficient_of_variation__20250701,B03_coefficient_of_variation__20250801,B03_coefficient_of_variation__20250901,B03_max__20241001,B03_max__20241101,B03_max__20241201,B03_max__20250101,B03_max__20250201,B03_max__20250301,B03_max__20250401,B03_max__20250501,B03_max__20250601,B03_max__20250701,B03_max__20250801,B03_max__20250901,B03_mean__20241001,B03_mean__20241101,B03_mean__20241201,B03_mean__20250101,B03_mean__20250201,B03_mean__20250301,B03_mean__20250401,B03_mean__20250501,B03_mean__20250601,B03_mean__20250701,B03_mean__20250801,B03_mean__20250901,B03_median__20241001,B03_median__20241101,B03_median__20241201,B03_median__20250101,B03_median__20250201,B03_median__20250301,B03_median__20250401,B03_median__20250501,B03_median__20250601,B03_median__20250701,B03_median__20250801,B03_median__20250901,B03_min__20241001,B03_min__20241101,B03_min__20241201,B03_min__20250101,B03_min__20250201,B03_min__20250301,B03_min__20250401,B03_min__20250501,B03_min__20250601,B03_min__20250701,B03_min__20250801,B03_min__20250901,B03_range__20241001,B03_range__20241101,B03_range__20241201,B03_range__20250101,B03_range__20250201,B03_range__20250301,B03_range__20250401,B03_range__20250501,B03_range__20250601,B03_range__20250701,B03_range__20250801,B03_range__20250901,B03_sd__20241001,B03_sd__20241101,B03_sd__20241201,B03_sd__20250101,B03_sd__20250201,B03_sd__20250301,B03_sd__20250401,B03_sd__20250501,B03_sd__20250601,B03_sd__20250701,B03_sd__20250801,B03_sd__20250901,B03_variance__20241001,B03_variance__20241101,B03_variance__20241201,B03_variance__20250101,B03_variance__20250201,B03_variance__20250301,B03_variance__20250401,B03_variance__20250501,B03_variance__20250601,B03_variance__20250701,B03_variance__20250801,B03_variance__20250901,B04_coefficient_of_variation__20241001,B04_coefficient_of_variation__20241101,B04_coefficient_of_variation__20241201,B04_coefficient_of_variation__20250101,B04_coefficient_of_variation__20250201,B04_coefficient_of_variation__20250301,B04_coefficient_of_variation__20250401,B04_coefficient_of_variation__20250501,B04_coefficient_of_variation__20250601,B04_coefficient_of_variation__20250701,B04_coefficient_of_variation__20250801,B04_coefficient_of_variation__20250901,B04_max__20241001,B04_max__20241101,B04_max__20241201,B04_max__20250101,B04_max__20250201,B04_max__20250301,B04_max__20250401,B04_max__20250501,B04_max__20250601,B04_max__20250701,B04_max__20250801,B04_max__20250901,B04_mean__20241001,B04_mean__20241101,B04_mean__20241201,B04_mean__20250101,B04_mean__20250201,B04_mean__20250301,B04_mean__20250401,B04_mean__20250501,B04_mean__20250601,B04_mean__20250701,B04_mean__20250801,B04_mean__20250901,B04_median__20241001,B04_median__20241101,B04_median__20241201,B04_median__20250101,B04_median__20250201,B04_median__20250301,B04_median__20250401,B04_median__20250501,B04_median__20250601,B04_median__20250701,B04_median__20250801,B04_median__20250901,B04_min__20241001,B04_min__20241101,B04_min__20241201,B04_min__20250101,B04_min__20250201,B04_min__20250301,B04_min__20250401,B04_min__20250501,B04_min__20250601,B04_min__20250701,B04_min__20250801,B04_min__20250901,B04_range__20241001,B04_range__20241101,B04_range__20241201,B04_range__20250101,B04_range__20250201,B04_range__20250301,B04_range__20250401,B04_range__20250501,B04_range__20250601,B04_range__20250701,B04_range__20250801,B04_range__20250901,B04_sd__20241001,B04_sd__20241101,B04_sd__20241201,B04_sd__20250101,B04_sd__20250201,B04_sd__20250301,B04_sd__20250401,B04_sd__20250501,B04_sd__20250601,B04_sd__20250701,B04_sd__20250801,B04_sd__20250901,B04_variance__20241001,B04_variance__20241101,B04_variance__20241201,B04_variance__20250101,B04_variance__20250201,B04_variance__20250301,B04_variance__20250401,B04_variance__20250501,B04_variance__20250601,B04_variance__20250701,B04_variance__20250801,B04_variance__20250901,B05_coefficient_of_variation__20241001,B05_coefficient_of_variation__20241101,B05_coefficient_of_variation__20241201,B05_coefficient_of_variation__20250101,B05_coefficient_of_variation__20250201,B05_coefficient_of_variation__20250301,B05_coefficient_of_variation__20250401,B05_coefficient_of_variation__20250501,B05_coefficient_of_variation__20250601,B05_coefficient_of_variation__20250701,B05_coefficient_of_variation__20250801,B05_coefficient_of_variation__20250901,B05_max__20241001,B05_max__20241101,B05_max__20241201,B05_max__20250101,B05_max__20250201,B05_max__20250301,B05_max__20250401,B05_max__20250501,B05_max__20250601,B05_max__20250701,B05_max__20250801,B05_max__20250901,B05_mean__20241001,B05_mean__20241101,B05_mean__20241201,B05_mean__20250101,B05_mean__20250201,B05_mean__20250301,B05_mean__20250401,B05_mean__20250501,B05_mean__20250601,B05_mean__20250701,B05_mean__20250801,B05_mean__20250901,B05_median__20241001,B05_median__20241101,B05_median__20241201,B05_median__20250101,B05_median__20250201,B05_median__20250301,B05_median__20250401,B05_median__20250501,B05_median__20250601,B05_median__20250701,B05_median__20250801,B05_median__20250901,B05_min__20241001,B05_min__20241101,B05_min__20241201,B05_min__20250101,B05_min__20250201,B05_min__20250301,B05_min__20250401,B05_min__20250501,B05_min__20250601,B05_min__20250701,B05_min__20250801,B05_min__20250901,B05_range__20241001,B05_range__20241101,B05_range__20241201,B05_range__20250101,B05_range__20250201,B05_range__20250301,B05_range__20250401,B05_range__20250501,B05_range__20250601,B05_range__20250701,B05_range__20250801,B05_range__20250901,B05_sd__20241001,B05_sd__20241101,B05_sd__20241201,B05_sd__20250101,B05_sd__20250201,B05_sd__20250301,B05_sd__20250401,B05_sd__20250501,B05_sd__20250601,B05_sd__20250701,B05_sd__20250801,B05_sd__20250901,B05_variance__20241001,B05_variance__20241101,B05_variance__20241201,B05_variance__20250101,B05_variance__20250201,B05_variance__20250301,B05_variance__20250401,B05_variance__20250501,B05_variance__20250601,B05_variance__20250701,B05_variance__20250801,B05_variance__20250901,B08_coefficient_of_variation__20241001,B08_coefficient_of_variation__20241101,B08_coefficient_of_variation__20241201,B08_coefficient_of_variation__20250101,B08_coefficient_of_variation__20250201,B08_coefficient_of_variation__20250301,B08_coefficient_of_variation__20250401,B08_coefficient_of_variation__20250501,B08_coefficient_of_variation__20250601,B08_coefficient_of_variation__20250701,B08_coefficient_of_variation__20250801,B08_coefficient_of_variation__20250901,B08_max__20241001,B08_max__20241101,B08_max__20241201,B08_max__20250101,B08_max__20250201,B08_max__20250301,B08_max__20250401,B08_max__20250501,B08_max__20250601,B08_max__20250701,B08_max__20250801,B08_max__20250901,B08_mean__20241001,B08_mean__20241101,B08_mean__20241201,B08_mean__20250101,B08_mean__20250201,B08_mean__20250301,B08_mean__20250401,B08_mean__20250501,B08_mean__20250601,B08_mean__20250701,B08_mean__20250801,B08_mean__20250901,B08_median__20241001,B08_median__20241101,B08_median__20241201,B08_median__20250101,B08_median__20250201,B08_median__20250301,B08_median__20250401,B08_median__20250501,B08_median__20250601,B08_median__20250701,B08_median__20250801,B08_median__20250901,B08_min__20241001,B08_min__20241101,B08_min__20241201,B08_min__20250101,B08_min__20250201,B08_min__20250301,B08_min__20250401,B08_min__20250501,B08_min__20250601,B08_min__20250701,B08_min__20250801,B08_min__20250901,B08_range__20241001,B08_range__20241101,B08_range__20241201,B08_range__20250101,B08_range__20250201,B08_range__20250301,B08_range__20250401,B08_range__20250501,B08_range__20250601,B08_range__20250701,B08_range__20250801,B08_range__20250901,B08_sd__20241001,B08_sd__20241101,B08_sd__20241201,B08_sd__20250101,B08_sd__20250201,B08_sd__20250301,B08_sd__20250401,B08_sd__20250501,B08_sd__20250601,B08_sd__20250701,B08_sd__20250801,B08_sd__20250901,B08_variance__20241001,B08_variance__20241101,B08_variance__20241201,B08_variance__20250101,B08_variance__20250201,B08_variance__20250301,B08_variance__20250401,B08_variance__20250501,B08_variance__20250601,B08_variance__20250701,B08_variance__20250801,B08_variance__20250901,B11_coefficient_of_variation__20241001,B11_coefficient_of_variation__20241101,B11_coefficient_of_variation__20241201,B11_coefficient_of_variation__20250101,B11_coefficient_of_variation__20250201,B11_coefficient_of_variation__20250301,B11_coefficient_of_variation__20250401,B11_coefficient_of_variation__20250501,B11_coefficient_of_variation__20250601,B11_coefficient_of_variation__20250701,B11_coefficient_of_variation__20250801,B11_coefficient_of_variation__20250901,B11_max__20241001,B11_max__20241101,B11_max__20241201,B11_max__20250101,B11_max__20250201,B11_max__20250301,B11_max__20250401,B11_max__20250501,B11_max__20250601,B11_max__20250701,B11_max__20250801,B11_max__20250901,B11_mean__20241001,B11_mean__20241101,B11_mean__20241201,B11_mean__20250101,B11_mean__20250201,B11_mean__20250301,B11_mean__20250401,B11_mean__20250501,B11_mean__20250601,B11_mean__20250701,B11_mean__20250801,B11_mean__20250901,B11_median__20241001,B11_median__20241101,B11_median__20241201,B11_median__20250101,B11_median__20250201,B11_median__20250301,B11_median__20250401,B11_median__20250501,B11_median__20250601,B11_median__20250701,B11_median__20250801,B11_median__20250901,B11_min__20241001,B11_min__20241101,B11_min__20241201,B11_min__20250101,B11_min__20250201,B11_min__20250301,B11_min__20250401,B11_min__20250501,B11_min__20250601,B11_min__20250701,B11_min__20250801,B11_min__20250901,B11_range__20241001,B11_range__20241101,B11_range__20241201,B11_range__20250101,B11_range__20250201,B11_range__20250301,B11_range__20250401,B11_range__20250501,B11_range__20250601,B11_range__20250701,B11_range__20250801,B11_range__20250901,B11_sd__20241001,B11_sd__20241101,B11_sd__20241201,B11_sd__20250101,B11_sd__20250201,B11_sd__20250301,B11_sd__20250401,B11_sd__20250501,B11_sd__20250601,B11_sd__20250701,B11_sd__20250801,B11_sd__20250901,B11_variance__20241001,B11_variance__20241101,B11_variance__20241201,B11_variance__20250101,B11_variance__20250201,B11_variance__20250301,B11_variance__20250401,B11_variance__20250501,B11_variance__20250601,B11_variance__20250701,B11_variance__20250801,B11_variance__20250901,B12_coefficient_of_variation__20241001,B12_coefficient_of_variation__20241101,B12_coefficient_of_variation__20241201,B12_coefficient_of_variation__20250101,B12_coefficient_of_variation__20250201,B12_coefficient_of_variation__20250301,B12_coefficient_of_variation__20250401,B12_coefficient_of_variation__20250501,B12_coefficient_of_variation__20250601,B12_coefficient_of_variation__20250701,B12_coefficient_of_variation__20250801,B12_coefficient_of_variation__20250901,B12_max__20241001,B12_max__20241101,B12_max__20241201,B12_max__20250101,B12_max__20250201,B12_max__20250301,B12_max__20250401,B12_max__20250501,B12_max__20250601,B12_max__20250701,B12_max__20250801,B12_max__20250901,B12_mean__20241001,B12_mean__20241101,B12_mean__20241201,B12_mean__20250101,B12_mean__20250201,B12_mean__20250301,B12_mean__20250401,B12_mean__20250501,B12_mean__20250601,B12_mean__20250701,B12_mean__20250801,B12_mean__20250901,B12_median__20241001,B12_median__20241101,B12_median__20241201,B12_median__20250101,B12_median__20250201,B12_median__20250301,B12_median__20250401,B12_median__20250501,B12_median__20250601,B12_median__20250701,B12_median__20250801,B12_median__20250901,B12_min__20241001,B12_min__20241101,B12_min__20241201,B12_min__20250101,B12_min__20250201,B12_min__20250301,B12_min__20250401,B12_min__20250501,B12_min__20250601,B12_min__20250701,B12_min__20250801,B12_min__20250901,B12_range__20241001,B12_range__20241101,B12_range__20241201,B12_range__20250101,B12_range__20250201,B12_range__20250301,B12_range__20250401,B12_range__20250501,B12_range__20250601,B12_range__20250701,B12_range__20250801,B12_range__20250901,B12_sd__20241001,B12_sd__20241101,B12_sd__20241201,B12_sd__20250101,B12_sd__20250201,B12_sd__20250301,B12_sd__20250401,B12_sd__20250501,B12_sd__20250601,B12_sd__20250701,B12_sd__20250801,B12_sd__20250901,B12_variance__20241001,B12_variance__20241101,B12_variance__20241201,B12_variance__20250101,B12_variance__20250201,B12_variance__20250301,B12_variance__20250401,B12_variance__20250501,B12_variance__20250601,B12_variance__20250701,B12_variance__20250801,B12_variance__20250901,EVI_coefficient_of_variation__20241001,EVI_coefficient_of_variation__20241101,EVI_coefficient_of_variation__20241201,EVI_coefficient_of_variation__20250101,EVI_coefficient_of_variation__20250201,EVI_coefficient_of_variation__20250301,EVI_coefficient_of_variation__20250401,EVI_coefficient_of_variation__20250501,EVI_coefficient_of_variation__20250601,EVI_coefficient_of_variation__20250701,EVI_coefficient_of_variation__20250801,EVI_coefficient_of_variation__20250901,EVI_max__20241001,EVI_max__20241101,EVI_max__20241201,EVI_max__20250101,EVI_max__20250201,EVI_max__20250301,EVI_max__20250401,EVI_max__20250501,EVI_max__20250601,EVI_max__20250701,EVI_max__20250801,EVI_max__20250901,EVI_mean__20241001,EVI_mean__20241101,EVI_mean__20241201,EVI_mean__20250101,EVI_mean__20250201,EVI_mean__20250301,EVI_mean__20250401,EVI_mean__20250501,EVI_mean__20250601,EVI_mean__20250701,EVI_mean__20250801,EVI_mean__20250901,EVI_median__20241001,EVI_median__20241101,EVI_median__20241201,EVI_median__20250101,EVI_median__20250201,EVI_median__20250301,EVI_median__20250401,EVI_median__20250501,EVI_median__20250601,EVI_median__20250701,EVI_median__20250801,EVI_median__20250901,EVI_min__20241001,EVI_min__20241101,EVI_min__20241201,EVI_min__20250101,EVI_min__20250201,EVI_min__20250301,EVI_min__20250401,EVI_min__20250501,EVI_min__20250601,EVI_min__20250701,EVI_min__20250801,EVI_min__20250901,EVI_range__20241001,EVI_range__20241101,EVI_range__20241201,EVI_range__20250101,EVI_range__20250201,EVI_range__20250301,EVI_range__20250401,EVI_range__20250501,EVI_range__20250601,EVI_range__20250701,EVI_range__20250801,EVI_range__20250901,EVI_sd__20241001,EVI_sd__20241101,EVI_sd__20241201,EVI_sd__20250101,EVI_sd__20250201,EVI_sd__20250301,EVI_sd__20250401,EVI_sd__20250501,EVI_sd__20250601,EVI_sd__20250701,EVI_sd__20250801,EVI_sd__20250901,EVI_variance__20241001,EVI_variance__20241101,EVI_variance__20241201,EVI_variance__20250101,EVI_variance__20250201,EVI_variance__20250301,EVI_variance__20250401,EVI_variance__20250501,EVI_variance__20250601,EVI_variance__20250701,EVI_variance__20250801,EVI_variance__20250901,NDMI_coefficient_of_variation__20241001,NDMI_coefficient_of_variation__20241101,NDMI_coefficient_of_variation__20241201,NDMI_coefficient_of_variation__20250101,NDMI_coefficient_of_variation__20250201,NDMI_coefficient_of_variation__20250301,NDMI_coefficient_of_variation__20250401,NDMI_coefficient_of_variation__20250501,NDMI_coefficient_of_variation__20250601,NDMI_coefficient_of_variation__20250701,NDMI_coefficient_of_variation__20250801,NDMI_coefficient_of_variation__20250901,NDMI_max__20241001,NDMI_max__20241101,NDMI_max__20241201,NDMI_max__20250101,NDMI_max__20250201,NDMI_max__20250301,NDMI_max__20250401,NDMI_max__20250501,NDMI_max__20250601,NDMI_max__20250701,NDMI_max__20250801,NDMI_max__20250901,NDMI_mean__20241001,NDMI_mean__20241101,NDMI_mean__20241201,NDMI_mean__20250101,NDMI_mean__20250201,NDMI_mean__20250301,NDMI_mean__20250401,NDMI_mean__20250501,NDMI_mean__20250601,NDMI_mean__20250701,NDMI_mean__20250801,NDMI_mean__20250901,NDMI_median__20241001,NDMI_median__20241101,NDMI_median__20241201,NDMI_median__20250101,NDMI_median__20250201,NDMI_median__20250301,NDMI_median__20250401,NDMI_median__20250501,NDMI_median__20250601,NDMI_median__20250701,NDMI_median__20250801,NDMI_median__20250901,NDMI_min__20241001,NDMI_min__20241101,NDMI_min__20241201,NDMI_min__20250101,NDMI_min__20250201,NDMI_min__20250301,NDMI_min__20250401,NDMI_min__20250501,NDMI_min__20250601,NDMI_min__20250701,NDMI_min__20250801,NDMI_min__20250901,NDMI_range__20241001,NDMI_range__20241101,NDMI_range__20241201,NDMI_range__20250101,NDMI_range__20250201,NDMI_range__20250301,NDMI_range__20250401,NDMI_range__20250501,NDMI_range__20250601,NDMI_range__20250701,NDMI_range__20250801,NDMI_range__20250901,NDMI_sd__20241001,NDMI_sd__20241101,NDMI_sd__20241201,NDMI_sd__20250101,NDMI_sd__20250201,NDMI_sd__20250301,NDMI_sd__20250401,NDMI_sd__20250501,NDMI_sd__20250601,NDMI_sd__20250701,NDMI_sd__20250801,NDMI_sd__20250901,NDMI_variance__20241001,NDMI_variance__20241101,NDMI_variance__20241201,NDMI_variance__20250101,NDMI_variance__20250201,NDMI_variance__20250301,NDMI_variance__20250401,NDMI_variance__20250501,NDMI_variance__20250601,NDMI_variance__20250701,NDMI_variance__20250801,NDMI_variance__20250901,NDRE_coefficient_of_variation__20241001,NDRE_coefficient_of_variation__20241101,NDRE_coefficient_of_variation__20241201,NDRE_coefficient_of_variation__20250101,NDRE_coefficient_of_variation__20250201,NDRE_coefficient_of_variation__20250301,NDRE_coefficient_of_variation__20250401,NDRE_coefficient_of_variation__20250501,NDRE_coefficient_of_variation__20250601,NDRE_coefficient_of_variation__20250701,NDRE_coefficient_of_variation__20250801,NDRE_coefficient_of_variation__20250901,NDRE_max__20241001,NDRE_max__20241101,NDRE_max__20241201,NDRE_max__20250101,NDRE_max__20250201,NDRE_max__2025030

In [4]:
gdf_parcels = gdf_parcels[gdf_parcels[class_column] != "jjjj"]
label_counts = gdf_parcels[class_column].value_counts()
print(f"Number of unique labels: {len(label_counts)}")
print(gdf_parcels[class_column].value_counts())
print(50*"-")
rare_labels = label_counts[label_counts < 5].index
gdf_parcels.loc[gdf_parcels[class_column].isin(rare_labels), class_column] = "9999"
print(f"Number of unique labels after grouping rare labels: {len(gdf_parcels[class_column].value_counts())}")
print(gdf_parcels[class_column].value_counts())

cond = gdf_parcels[class_column] == "9999"
print(50*"-")
print(f"Excluded parcels with label '9999': {cond.sum()} out of {len(gdf_parcels)}")
gdf_parcels = gdf_parcels[~cond].copy()

Number of unique labels: 25
crop_category
ΚΤΗΝΟΤΡΟΦΙΚΑ ΦΥΤΑ                                       305
ΒΑΜΒΑΚΙ                                                 224
ΣΚΛΗΡΟΣ ΣΙΤΟΣ                                           149
ΔΑΣΙΚΑ ΔΕΝΤΡΑ                                            95
ΕΝΕΡΓΕΙΑΚΕΣ ΚΑΛΛΙΕΡΓΕΙΕΣ                                 82
ΒΟΣΚΟΤΟΠΟΣ                                               61
ΛΟΙΠΑ ΣΙΤΗΡΑ                                             50
ΑΡΩΜΑΤΙΚΑ ΦΥΤΑ                                           49
ΑΓΡΑΝΑΠΑΥΣΗ                                              41
ΕΛΑΙΩΝΕΣ                                                 26
ΓΗ ΠΟΥ ΔΕΝ ΕΝΤΑΣΣΕΤΑΙ ΣΕ ΚΑΛΛΙΕΡΓΗΤΙΚΗ ΔΡΑΣΤΗΡΙΟΤΗΤΑ     13
ΑΜΠΕΛΩΝΕΣ                                                11
ΑΚΡΟΔΡΥΑ (ΚΑΡΠΟΙ ΜΕ ΚΕΛΥΦΟΣ)                              9
ΑΡΑΒΟΣΙΤΟΣ                                                8
ΟΣΠΡΙΑ ΒΡΩΣΙΜΑ                                            7
ΠΟΡΤΟΚΑΛΙΑ ΠΡΟΣ ΧΥΜΟΠΟΙΗΣΗ                                5
ΠΥΡΗΝΟΚΑΡΠΑ                                               5
ΕΛΑΙΟΥΧΟΙ ΣΠΟΡΟΙ                                          5
KHPEYTIKA                                                 5
ΚΑΠΝΟΣ                                                    4
ΣΠΟΡΟΠΑΡΑΓΩΓΗ                                             3
ΡΟΔΑΚΙΝΙΕΣ                                                3
ΕΣΠΕΡΙΔΟΕΙΔΗ                                              2
ΜΗΛΟΕΙΔΗ                                                  2
ΖΑΧΑΡΟΤΕΥΤΛΑ                                              1
Name: count, dtype: int64
--------------------------------------------------
Number of unique labels after grouping rare labels: 20
crop_category
ΚΤΗΝΟΤΡΟΦΙΚΑ ΦΥΤΑ                                       305
ΒΑΜΒΑΚΙ                                                 224
ΣΚΛΗΡΟΣ ΣΙΤΟΣ                                           149
ΔΑΣΙΚΑ ΔΕΝΤΡΑ                                            95
ΕΝΕΡΓΕΙΑΚΕΣ ΚΑΛΛΙΕΡΓΕΙΕΣ                                 82
ΒΟΣΚΟΤΟΠΟΣ                                               61
ΛΟΙΠΑ ΣΙΤΗΡΑ                                             50
ΑΡΩΜΑΤΙΚΑ ΦΥΤΑ                                           49
ΑΓΡΑΝΑΠΑΥΣΗ                                              41
ΕΛΑΙΩΝΕΣ                                                 26
9999                                                     15
ΓΗ ΠΟΥ ΔΕΝ ΕΝΤΑΣΣΕΤΑΙ ΣΕ ΚΑΛΛΙΕΡΓΗΤΙΚΗ ΔΡΑΣΤΗΡΙΟΤΗΤΑ     13
ΑΜΠΕΛΩΝΕΣ                                                11
ΑΚΡΟΔΡΥΑ (ΚΑΡΠΟΙ ΜΕ ΚΕΛΥΦΟΣ)                              9
ΑΡΑΒΟΣΙΤΟΣ                                                8
ΟΣΠΡΙΑ ΒΡΩΣΙΜΑ                                            7
ΠΟΡΤΟΚΑΛΙΑ ΠΡΟΣ ΧΥΜΟΠΟΙΗΣΗ                                5
ΠΥΡΗΝΟΚΑΡΠΑ                                               5
KHPEYTIKA                                                 5
ΕΛΑΙΟΥΧΟΙ ΣΠΟΡΟΙ                                          5
Name: count, dtype: int64
--------------------------------------------------
Excluded parcels with label '9999': 15 out of 1165

In [5]:
df_features = io_l.read_data(str(PROPOSED_FEATURES_PATH))
display(df_features.head())

proposed_features = df_features[df_features["proposed_action"]=="use"]["feature"].tolist()
print(f"Proposed features: {len(proposed_features)}")
proposed_features

Reading file: C:/work_dir/neuro_2024-2025a/2_eo_results_eda_fill/tables/feature_selection/feature_selection_proposal.csv

,selection_order,feature,feature_type,proposed_action,primary_reason,association_method,effect_size,association_strength,qvalue,missing_percent,redundant_with,redundancy_measure,passes_hard_exclusions,passes_data_quality,passes_target_evidence,passes_redundancy,passes_shortlist_limit
0,1,GAIOIKANOT,categorical,use,priority target ...,bias_corrected_c...,0.4060000000,moderate,0.0000000000,0.0000000000,NaN,NaN,True,True,True,True,True
1,2,elevation_mean_m,numeric,use,priority target ...,kruskal_epsilon_...,0.3360000000,large,0.0000000000,0.0000000000,NaN,NaN,True,True,True,True,True
2,3,NDWI_median__202...,numeric,use,priority target ...,kruskal_epsilon_...,0.3114000000,large,0.0000000000,0.0000000000,NaN,NaN,True,True,True,True,True
3,4,NDVI_median__202...,numeric,use,priority target ...,kruskal_epsilon_...,0.2866000000,large,0.0000000000,0.0858000000,NaN,NaN,True,True,True,True,True
4,5,NDVI_median__202...,numeric,use,priority target ...,kruskal_epsilon_...,0.2835000000,large,0.0000000000,0.0000000000,NaN,NaN,True,True,True,True,True

Proposed features: 28

['GAIOIKANOT',
 'elevation_mean_m',
 'NDWI_median__20241001',
 'NDVI_median__20241201',
 'NDVI_median__20241101',
 'NDMI_median__20241001',
 'EVI_median__20241001',
 'NDMI_median__20241101',
 'EVI_median__20241201',
 'NDVI_median__20250901',
 'NDVI_median__20250701',
 'NDRE_median__20250101',
 'NDRE_median__20250301',
 'NDVI_median__20250401',
 'NDVI_median__20250501',
 'NDVI_median__20250601',
 'NDWI_median__20250101',
 'NDMI_median__20250101',
 'NDVI_median__20250201',
 'NDMI_median__20250201',
 'EVI_median__20250101',
 'NDMI_median__20250301',
 'EVI_median__20250201',
 'NDMI_median__20241201',
 'NDMI_median__20250901',
 'NDMI_median__20250701',
 'data_reliability_score',
 'NDMI_median__20250601']

In [6]:
gdf_parcels = gdf_parcels.to_crs(2100)
gdf_parcels["x"] = gdf_parcels.centroid.x
gdf_parcels["y"] = gdf_parcels.centroid.y

base_cols = [parcel_id_column, class_column, "geometry", "data_reliability_score", "geom_shape_complexity_score"]
extra_features = ["elevation_mean_m", "GAIOIKANOT", "x", "y"]
temporal_features = ("_median", "_sd", "_range",)
selected_indices = ("NDMI", "NDRE", "SAVI", "NDVI", "EVI", "NDWI",)
original_features = [x for x in gdf_parcels.columns if any(keyword in x for keyword in temporal_features) and any(idx in x for idx in selected_indices)]

gdf_parcels = gdf_parcels[base_cols + original_features + extra_features].copy()
features = original_features + extra_features

gdf_parcels = gdf_parcels[gdf_parcels[class_column] != 9999].copy()
print(f"Final features for modeling ({len(features)} features): {features}")
display(gdf_parcels.head(3))

Final features for modeling (220 features): ['EVI_median__20241001', 'EVI_median__20241101', 'EVI_median__20241201', 'EVI_median__20250101', 'EVI_median__20250201', 'EVI_median__20250301', 'EVI_median__20250401', 'EVI_median__20250501', 'EVI_median__20250601', 'EVI_median__20250701', 'EVI_median__20250801', 'EVI_median__20250901', 'EVI_range__20241001', 'EVI_range__20241101', 'EVI_range__20241201', 'EVI_range__20250101', 'EVI_range__20250201', 'EVI_range__20250301', 'EVI_range__20250401', 'EVI_range__20250501', 'EVI_range__20250601', 'EVI_range__20250701', 'EVI_range__20250801', 'EVI_range__20250901', 'EVI_sd__20241001', 'EVI_sd__20241101', 'EVI_sd__20241201', 'EVI_sd__20250101', 'EVI_sd__20250201', 'EVI_sd__20250301', 'EVI_sd__20250401', 'EVI_sd__20250501', 'EVI_sd__20250601', 'EVI_sd__20250701', 'EVI_sd__20250801', 'EVI_sd__20250901', 'NDMI_median__20241001', 'NDMI_median__20241101', 'NDMI_median__20241201', 'NDMI_median__20250101', 'NDMI_median__20250201', 'NDMI_median__20250301', 'NDMI_median__20250401', 'NDMI_median__20250501', 'NDMI_median__20250601', 'NDMI_median__20250701', 'NDMI_median__20250801', 'NDMI_median__20250901', 'NDMI_range__20241001', 'NDMI_range__20241101', 'NDMI_range__20241201', 'NDMI_range__20250101', 'NDMI_range__20250201', 'NDMI_range__20250301', 'NDMI_range__20250401', 'NDMI_range__20250501', 'NDMI_range__20250601', 'NDMI_range__20250701', 'NDMI_range__20250801', 'NDMI_range__20250901', 'NDMI_sd__20241001', 'NDMI_sd__20241101', 'NDMI_sd__20241201', 'NDMI_sd__20250101', 'NDMI_sd__20250201', 'NDMI_sd__20250301', 'NDMI_sd__20250401', 'NDMI_sd__20250501', 'NDMI_sd__20250601', 'NDMI_sd__20250701', 'NDMI_sd__20250801', 'NDMI_sd__20250901', 'NDRE_median__20241001', 'NDRE_median__20241101', 'NDRE_median__20241201', 'NDRE_median__20250101', 'NDRE_median__20250201', 'NDRE_median__20250301', 'NDRE_median__20250401', 'NDRE_median__20250501', 'NDRE_median__20250601', 'NDRE_median__20250701', 'NDRE_median__20250801', 'NDRE_median__20250901', 'NDRE_range__20241001', 'NDRE_range__20241101', 'NDRE_range__20241201', 'NDRE_range__20250101', 'NDRE_range__20250201', 'NDRE_range__20250301', 'NDRE_range__20250401', 'NDRE_range__20250501', 'NDRE_range__20250601', 'NDRE_range__20250701', 'NDRE_range__20250801', 'NDRE_range__20250901', 'NDRE_sd__20241001', 'NDRE_sd__20241101', 'NDRE_sd__20241201', 'NDRE_sd__20250101', 'NDRE_sd__20250201', 'NDRE_sd__20250301', 'NDRE_sd__20250401', 'NDRE_sd__20250501', 'NDRE_sd__20250601', 'NDRE_sd__20250701', 'NDRE_sd__20250801', 'NDRE_sd__20250901', 'NDVI_median__20241001', 'NDVI_median__20241101', 'NDVI_median__20241201', 'NDVI_median__20250101', 'NDVI_median__20250201', 'NDVI_median__20250301', 'NDVI_median__20250401', 'NDVI_median__20250501', 'NDVI_median__20250601', 'NDVI_median__20250701', 'NDVI_median__20250801', 'NDVI_median__20250901', 'NDVI_range__20241001', 'NDVI_range__20241101', 'NDVI_range__20241201', 'NDVI_range__20250101', 'NDVI_range__20250201', 'NDVI_range__20250301', 'NDVI_range__20250401', 'NDVI_range__20250501', 'NDVI_range__20250601', 'NDVI_range__20250701', 'NDVI_range__20250801', 'NDVI_range__20250901', 'NDVI_sd__20241001', 'NDVI_sd__20241101', 'NDVI_sd__20241201', 'NDVI_sd__20250101', 'NDVI_sd__20250201', 'NDVI_sd__20250301', 'NDVI_sd__20250401', 'NDVI_sd__20250501', 'NDVI_sd__20250601', 'NDVI_sd__20250701', 'NDVI_sd__20250801', 'NDVI_sd__20250901', 'NDWI_median__20241001', 'NDWI_median__20241101', 'NDWI_median__20241201', 'NDWI_median__20250101', 'NDWI_median__20250201', 'NDWI_median__20250301', 'NDWI_median__20250401', 'NDWI_median__20250501', 'NDWI_median__20250601', 'NDWI_median__20250701', 'NDWI_median__20250801', 'NDWI_median__20250901', 'NDWI_range__20241001', 'NDWI_range__20241101', 'NDWI_range__20241201', 'NDWI_range__20250101', 'NDWI_range__20250201', 'NDWI_range__20250301', 'NDWI_range__20250401', 'NDWI_range__20250501', 'NDWI_range__20250601', 'NDWI_range__20250701', 'NDWI_range__20250801', 'NDWI_range__20250901', 'NDWI_sd__20241001', 'NDWI_sd__20241101', 'NDWI_sd__20241201', 'NDWI_sd__20250101', 'NDWI_sd__20250201', 'NDWI_sd__20250301', 'NDWI_sd__20250401', 'NDWI_sd__20250501', 'NDWI_sd__20250601', 'NDWI_sd__20250701', 'NDWI_sd__20250801', 'NDWI_sd__20250901', 'SAVI_median__20241001', 'SAVI_median__20241101', 'SAVI_median__20241201', 'SAVI_median__20250101', 'SAVI_median__20250201', 'SAVI_median__20250301', 'SAVI_median__20250401', 'SAVI_median__20250501', 'SAVI_median__20250601', 'SAVI_median__20250701', 'SAVI_median__20250801', 'SAVI_median__20250901', 'SAVI_range__20241001', 'SAVI_range__20241101', 'SAVI_range__20241201', 'SAVI_range__20250101', 'SAVI_range__20250201', 'SAVI_range__20250301', 'SAVI_range__20250401', 'SAVI_range__20250501', 'SAVI_range__20250601', 'SAVI_range__20250701', 'SAVI_range__20250801', 'SAVI_range__20250901', 'SAVI_sd__20241001', 'SAVI_sd__20241101', 'SAVI_sd__20241201', 'SAVI_sd__20250101', 'SAVI_sd__20250201', 'SAVI_sd__20250301', 'SAVI_sd__20250401', 'SAVI_sd__20250501', 'SAVI_sd__20250601', 'SAVI_sd__20250701', 'SAVI_sd__20250801', 'SAVI_sd__20250901', 'elevation_mean_m', 'GAIOIKANOT', 'x', 'y']

,parcel_id,crop_category,geometry,data_reliability_score,geom_shape_complexity_score,EVI_median__20241001,EVI_median__20241101,EVI_median__20241201,EVI_median__20250101,EVI_median__20250201,EVI_median__20250301,EVI_median__20250401,EVI_median__20250501,EVI_median__20250601,EVI_median__20250701,EVI_median__20250801,EVI_median__20250901,EVI_range__20241001,EVI_range__20241101,EVI_range__20241201,EVI_range__20250101,EVI_range__20250201,EVI_range__20250301,EVI_range__20250401,EVI_range__20250501,EVI_range__20250601,EVI_range__20250701,EVI_range__20250801,EVI_range__20250901,EVI_sd__20241001,EVI_sd__20241101,EVI_sd__20241201,EVI_sd__20250101,EVI_sd__20250201,EVI_sd__20250301,EVI_sd__20250401,EVI_sd__20250501,EVI_sd__20250601,EVI_sd__20250701,EVI_sd__20250801,EVI_sd__20250901,NDMI_median__20241001,NDMI_median__20241101,NDMI_median__20241201,NDMI_median__20250101,NDMI_median__20250201,NDMI_median__20250301,NDMI_median__20250401,NDMI_median__20250501,NDMI_median__20250601,NDMI_median__20250701,NDMI_median__20250801,NDMI_median__20250901,NDMI_range__20241001,NDMI_range__20241101,NDMI_range__20241201,NDMI_range__20250101,NDMI_range__20250201,NDMI_range__20250301,NDMI_range__20250401,NDMI_range__20250501,NDMI_range__20250601,NDMI_range__20250701,NDMI_range__20250801,NDMI_range__20250901,NDMI_sd__20241001,NDMI_sd__20241101,NDMI_sd__20241201,NDMI_sd__20250101,NDMI_sd__20250201,NDMI_sd__20250301,NDMI_sd__20250401,NDMI_sd__20250501,NDMI_sd__20250601,NDMI_sd__20250701,NDMI_sd__20250801,NDMI_sd__20250901,NDRE_median__20241001,NDRE_median__20241101,NDRE_median__20241201,NDRE_median__20250101,NDRE_median__20250201,NDRE_median__20250301,NDRE_median__20250401,NDRE_median__20250501,NDRE_median__20250601,NDRE_median__20250701,NDRE_median__20250801,NDRE_median__20250901,NDRE_range__20241001,NDRE_range__20241101,NDRE_range__20241201,NDRE_range__20250101,NDRE_range__20250201,NDRE_range__20250301,NDRE_range__20250401,NDRE_range__20250501,NDRE_range__20250601,NDRE_range__20250701,NDRE_range__20250801,NDRE_range__20250901,NDRE_sd__20241001,NDRE_sd__20241101,NDRE_sd__20241201,NDRE_sd__20250101,NDRE_sd__20250201,NDRE_sd__20250301,NDRE_sd__20250401,NDRE_sd__20250501,NDRE_sd__20250601,NDRE_sd__20250701,NDRE_sd__20250801,NDRE_sd__20250901,NDVI_median__20241001,NDVI_median__20241101,NDVI_median__20241201,NDVI_median__20250101,NDVI_median__20250201,NDVI_median__20250301,NDVI_median__20250401,NDVI_median__20250501,NDVI_median__20250601,NDVI_median__20250701,NDVI_median__20250801,NDVI_median__20250901,NDVI_range__20241001,NDVI_range__20241101,NDVI_range__20241201,NDVI_range__20250101,NDVI_range__20250201,NDVI_range__20250301,NDVI_range__20250401,NDVI_range__20250501,NDVI_range__20250601,NDVI_range__20250701,NDVI_range__20250801,NDVI_range__20250901,NDVI_sd__20241001,NDVI_sd__20241101,NDVI_sd__20241201,NDVI_sd__20250101,NDVI_sd__20250201,NDVI_sd__20250301,NDVI_sd__20250401,NDVI_sd__20250501,NDVI_sd__20250601,NDVI_sd__20250701,NDVI_sd__20250801,NDVI_sd__20250901,NDWI_median__20241001,NDWI_median__20241101,NDWI_median__20241201,NDWI_median__20250101,NDWI_median__20250201,NDWI_median__20250301,NDWI_median__20250401,NDWI_median__20250501,NDWI_median__20250601,NDWI_median__20250701,NDWI_median__20250801,NDWI_median__20250901,NDWI_range__20241001,NDWI_range__20241101,NDWI_range__20241201,NDWI_range__20250101,NDWI_range__20250201,NDWI_range__20250301,NDWI_range__20250401,NDWI_range__20250501,NDWI_range__20250601,NDWI_range__20250701,NDWI_range__20250801,NDWI_range__20250901,NDWI_sd__20241001,NDWI_sd__20241101,NDWI_sd__20241201,NDWI_sd__20250101,NDWI_sd__20250201,NDWI_sd__20250301,NDWI_sd__20250401,NDWI_sd__20250501,NDWI_sd__20250601,NDWI_sd__20250701,NDWI_sd__20250801,NDWI_sd__20250901,SAVI_median__20241001,SAVI_median__20241101,SAVI_median__20241201,SAVI_median__20250101,SAVI_median__20250201,SAVI_median__20250301,SAVI_median__20250401,SAVI_median__20250501,SAVI_median__20250601,SAVI_median__20250701,SAVI_median__20250801,SAVI_median__20250901,SAVI_range__20241001,SAVI_range__20241101,SAVI_range__20241201,SAVI_range__20250101,SAVI_range__20250201,SAVI_range__20250301,SAVI_range__20250401,SAVI_range__20250501,SAVI_range__20250601,SAVI_range__20250701,SAVI_range__20250801,SAVI_range__20250901,SAVI_sd__20241001,SAVI_sd__20241101,SAVI_sd__20241201,SAVI_sd__20250101,SAVI_sd__20250201,SAVI_sd__20250301,SAVI_sd__20250401,SAVI_sd__20250501,SAVI_sd__20250601,SAVI_sd__20250701,SAVI_sd__20250801,SAVI_sd__20250901,elevation_mean_m,GAIOIKANOT,x,y
0,552,ΕΝΕΡΓΕΙΑΚΕΣ ΚΑΛΛ...,POLYGON ((276662...,0.8300494827,1.0035650305,0.1106376648,0.0775117278,0.0798041150,0.1143037528,0.2182899117,0.3299211860,0.5593869686,0.5886694193,0.2712654471,0.1410439312,0.1146065071,0.1140175462,0.1890584975,0.1884644479,0.4492145777,0.2747471631,0.3542263508,0.5280439258,0.6604353786,0.6942611933,0.5306599140,0.3144756258,0.3083961010,0.2799670398,0.0383778077,0.0423964256,0.0748039885,0.0617391979,0.0883024170,0.1194616814,0.1587153225,0.1290343996,0.1054106537,0.0437202281,0.0405705703,0.0331858685,-0.2551724315,-0.2248230875,-0.1177094355,-0.0955440998,-0.0409717262,0.0696920305,0.3216329813,0.3704257011,0.0800000057,-0.0715752989,-0.1764297932,-0.2206624150,0.2602586150,0.2945734560,0.3466018438,0.3567946255,0.4041579366,0.5035702586,0.5460855961,0.4515050352,0.5903598070,0.4535401165,0.4140983522,0.3820267022,0.0452380506,0.0418464177,0.0991392680,0.0914973798,0.0828367124,0.1071320501,0.1288495058,0.0967754048,0.1153042358,0.0662860847,0.0547211057,0.0440116308,0.1528545320,0.1253263503,0.1423611194,0.1832347512,0.2355915904,0.3327882290,0.5258170962,0.5301507711,0.2407609969,0.1233219877,0.1180857345,0.1304611564,0.2845375538,0.2770481706,0.4168336391,0.3732278347,0.3010132611,0.3913825452,0.4678774476,0.4179983139,0.4617028534,0.3445197642,0.3936473429,0.3690285087,0.0551629597,0.0518629456,0.0991101285,0.1034364668,0.0748454491,0.0929138502,0.1099829042,0.0891042137,0.0933266027,0.0467120138,0.0497315189,0.0457902948,0.2364553064,0.2007083893,0.2324966937,0.3213895857,0.3969648182,0.5334476829,0.7797803879,0.7851761580,0.4382647276,0.2047048807,0.1971995682,0.2110450566,0.3820734918,0.3152809739,0.5665736198,0.5634813309,0.4858960509,0.5667124987,0.5872044563,0.4670005143,0.6410669684,0.5082128048,0.5059983730,0.4876520038,0.0625954475,0.0637885520,0.1572240435,0.1635132447,0.1253874461,0.1486559277,0.1506876214,0.0940727190,0.1450231600,0.0697795659,0.0690337155,0.0642795648,-0.3802971840,-0.3651551604,-0.3972366452,-0.4415450096,-0.4272960424,-0.5302137733,-0.6951645613,-0.6838013530,-0.5227394700,-0.3929349780,-0.3426523507,-0.3546110094,0.3128243387,0.2817364335,0.6623046398,0.5704145432,0.3996188641,0.3743267357,0.4163267612,0.3104033172,0.3574137390,0.3524883986,0.3666609526,0.3679938316,0.0472906619,0.0471753821,0.1981291122,0.1778666131,0.0945450275,0.0891142770,0.1010947934,0.0648183541,0.0682580044,0.0547954698,0.0545685851,0.0526787537,0.1168627366,0.0860306621,0.0837468728,0.1212213635,0.2024525702,0.3166729510,0.5237727165,0.5297981501,0.2800319195,0.1526912004,0.1198897287,0.1189617366,0.1900263429,0.1818674207,0.3015463948,0.3073889613,0.3167070150,0.4469716251,0.5188351274,0.4326378107,0.4384067059,0.3009074032,0.2947594523,0.2745015025,0.0374028220,0.0406922784,0.0667828133,0.0770925817,0.0748246791,0.1078999514,0.1319465781,0.0945210848,0.0903630628,0.0431589692,0.0393250180,0.0337117197,611.1272253418,T3T7-121-1-D1BN,276753.4855326796,4436725.3927100282
1,554,ΚΤΗΝΟΤΡΟΦΙΚΑ ΦΥΤΑ,POLYGON ((278217...,0.8375062846,0.6211679165,0.1085099131,0.0938298628,0.1078912765,0.1788445115,0.2575619221,0.4049782455,0.7201124430,0.6816211343,0.2738572955,0.1831563562,0.1902773827,0.1459551454,0.4083240032,0.3511473835,0.7302840352,0.2077567428,0.4467927516,0.6507186890,0.8889611959,0.5550278425,0.5128920078,0.4607912898,0.4642591476,0.4378584027,0.1044084211,0.0773043171,0.0990936177,0.0470960844,0.0805547815,0.1327365437,0.1404462136,0.1106855487,0.1111854804,0.0861065039,0.0936185161,0.0965169352,-0.1487207115,-0.1557682306,-0.0730676576,-0.0594660640,0.0068688951,0.1412764341,0.4443031847,0.4231570065,0.0762747601,-0.0391605981,-0.0919013992,-0.1180056259,0.6504369974,0.7503587604,0.5785900950,0.4970572889,0.4371495247,0.6090721488,0.5481840372,0.2905303538,0.5073919892,0.3893713653,0.3689974248,0.4163690209,0.1236348932,0.1198066689,0.1239389842,0.0866430284,0.0856410741,0.1174138658,0.1075989646,0.0740880801,0.1173111752,0.0698650787,0.0747919603,0.0853129627,0.1913175136,0.1561530828,0.1358983666,0.2668250501,0.2830266953,0.4026499093,0.6193286777,0.5811598301,0.3036437035,0.1869688779,0.2069279701,0.1856995821,0.5607213974,0.6945303082,0.4776628315,0.4021441340,0.3761861920,0.4420893192,0.4143911004,0.3718452752,0.4737682045,0.3868531287,0.3962347806,0.4371772110,0.1132000557,0.0950414684,0.1124921505,0.0948796845,0.0621923459,0.0836991359,0.0793110405,0.0738148963,0.1038872639,0.0779634682,0.0826212303,0.0953416281,0.2714441121,0.2452471703,0.3337620795,0.4499797225,0.4780049920,0.6270526052,0.8711590767,0.8413350582,0.4482942820,0.2484705299,0.2750775516,0.2450446486,0.6587976217,0.4899967611,0.6154762506,0.4464024901,0.4219324887,0.5701295137,0.4302317500,0.4924024642,0.6830009818,0.6365635395,0.6460090876,0.6735978127,0.1665908330,0.1069566374,0.1719215485,0.1304950128,0.0747805935,0.1262286472,0.0839308430,0.0688782161,0.1536192730,0.1149585951,0.1229550917,0.1439451137,-0.4038892686,-0.4130507112,-0.4501108825,-0.5498299003,-0.5310416818,-0.5995599031,-0.7677394152,-0.7345462441,-0.5603063107,-0.4163669348,-0.3998408318,-0.3826394379,0.4818151593,0.4600112438,1.0616773367,0.5986481905,0.3574041426,0.4145963788,0.3096604943,0.4514939189,0.4325357080,0.4553259015,0.5219929218,0.4716329873,0.1125794187,0.0988944834,0.2481372242,0.1529395851,0.0727086329,0.0805053746,0.0597650391,0.0596733129,0.0870334367,0.0795060601,0.0907921548,0.1040008926,0.1174477190,0.1019575894,0.1066945717,0.1885368228,0.2571935654,0.3872889876,0.6457015276,0.5959898829,0.2914540470,0.1905218661,0.1911634058,0.1536289603,0.3886646628,0.3433608413,0.2981295288,0.2181333452,0.2867266238,0.5052146912,0.4829872847,0.3723356724,0.4765316546,0.4241053462,0.4309272766,0.4224417508,0.1021550061,0.0776158793,0.0682907499,0.0585155387,0.0623018113,0.1094129436,0.1028826792,0.0716115657,0.0981899741,0.0792954320,0.0807069458,0.0928872092,599.4402609432,T7T3-121-1-D9BN,278301.4883010412,4438016.9995247768
2,555,ΚΤΗΝΟΤΡΟΦΙΚΑ ΦΥΤΑ,POLYGON ((274769...,0.8580636122,0.5572634284,0.0901840925,0.0827291757,0.0864057615,0.1304084212,0.2085767835,0.2943556011,0.5810806155,0.6965554357,0.2796534300,0.1497905701,0.1452105939,0.1543216407,0.4688726664,0.3692423403,0.3050810099,0.1671077013,0.2986771464,0.4256015420,0.6046247482,0.5749007463,0.5901767015,0.6176344752,0.4974639118,0.4692038000,0.0890071845,0.0609966785,0.0425400983,0.0331438592,0.0657518817,0.0822507157,0.1486700403,0.1155381460,0.1344020446,0.1063169588,0.0946737452,0.0900656337,-0.1400465816,-0.1344992220,-0.0772634745,-0.0502888858,-0.0165447351,0.0517985821,0.3612604141,0.4406292737,0.1336201131,-0.0229842234,-0.0771120787,-0.0915234089,0.6186277866,0.7194182873,0.5788332224,0.4342001379,0.3529374599,0.5133264065,0.5991927981,0.3638516963,0.5010026097,0.3452330232,0.3573437929,0.4296573400,0.0980068358,0.1028593570,0.1011164799,0.0818570757,0.0526297547,0.0839826897,0.1389921026,0.0804641868,0.1232265763,0.0689035258,0.0712205879,0.0768654383,0.1239031255,0.1235431284,0.1296296269,0.1898066849,0.2197623849,0.2678936422,0.5512799025,0.5820127130,0.2492770553,0.1213274375,0.1230125725,0.1410427988,0.5591821671,0.5571289659,0.4092575610,0.3716609478,0.3007862866,0.3250556588,0.4836415052,0.3682248890,0.5101960897,0.4044048190,0.4314264953,0.4592781365,0.0936427305,0.0818801524,0.0871877802,0.0888070982,0.0515640724,0.0569871668,0.1132006634,0.0811346816,0.1139760658,0.0815194328,0.0845962123,0.0870240550,0.1708184928,0.1870765835,0.2350365072,0.3099824786,0.3382646441,0.4261118770,0.8160060644,0.8359621763,0.4053923190,0.1815169305,0.1841970086,0.2106412947,0.6533540487,0.4891619682,0.4560030103,0.3962844610,0.4382743537,0.4864039123,0.5582913160,0.3505862951,0.7288470268,0.6506308317,0.6462888718,0.6361493468,0.1394032338,0.0921405373,0.1105753001,0.1191581294,0.0687191135,0.1066049415,0.1395532878,0.0700356245,0.1742243916,0.1281953590,0.1292260468,0.1358022662,-0.2844221294,-0.3278418481,-0.3768227100,-0.4246575534,-0.3831304312,-0.4515663087,-0.7096453905,-0.7216575742,-0.5073342919,-0.3499340415,-0.3076295257,-0.3226229250,0.4820804000,0.4100804329,0.7546668649,0.6241208911,0.4863782227,0.3138970733,0.3743047118,0.2598723173,0.4828129411,0.4595663548,0.4750467241,0.4785318673,0.1076217734,0.0928677221,0.1725138906,0.1684564428,0.0835123581,0.0649487108,0.0935428165,0.0577660157,0.0967892161,0.0901650265,0.0972906491,0.1044475668,0.0916986093,0.0849917009,0.0865132585,0.1328264773,0.2003481388,0.2741648853,0.5384392142,0.6021171808,0.2876869142,0.1553962529,0.1405507326,0.1496482044,0.4304920435,0.3681118190,0.2427728325,0.2053409964,0.2398815006,0.3567246795,0.5077836514,0.3683541715,0.5305737853,0.4783196747,0.4571961761,0.4397005439,0.0868413738,0.0635511139,0.0489541374,0.0550053679,0.0421609813,0.0722195025,0.1216829855,0.0746504475,0.1152832262,0.0933569894,0.0881186617,0.0865891263,663.8062877655,T3T7-121-4-D9QQ,274730.2565349285,4440045.9869523821

In [13]:
config = ClassificationPipelineConfig(
    project_dir=OUTPUT_PATH,
    target_column=class_column,
    feature_columns=features,
    id_column=parcel_id_column,

    apply_iqr=False,
    spatial_interpolation_method="nearest",  # None, nearest, idw, or kriging

    cv_folds=5,
    test_size=0.2,
    spatial_split=True,
    spatial_split_grid_size=30,
    spatial_split_method="by_row",
    random_state=SEED_NUMBER,

    scoring_primary="f1_macro",
    cv_ranking_method="score_minus_std",
    selection_type="soft_voting",
    top_voting_models=8,
    max_search_candidates=40,
    prediction_confidence_threshold=0.60,

    interpretability_top_models=7,
    interpretability_include_shap=False,

    optimize_class_probabilities=True,
    probability_multiplier_grid=(0.8, 1.0, 1.2, 1.5, 2.0),
    probability_optimization_iterations=2,
    probability_optimization_max_accuracy_drop=0.02,

    rank_confidence_enabled=True,
    force_retrain_models=False,
    class_reliability_enabled=False,

    label_balancing_method="random_oversample",
    lstm_temporal_statistics=temporal_features,
    selected_models=(
        "bagging",
        "bayesian",
        "decision_tree",
        "extra_trees",
        "random_forest",
        "gradient_boosting",
        "lightgbm",
        "xgboost",
        "support_vector_machine",
        "knn",
        "neural_network",
        # "keras_lstm",
   ),
    max_map_geometries=20000,
    open_html_report=True,
)

layer_features = max(16, min(len(features), 64))
config.tune_params["tensorflow_neural_network"]["model__hidden_layer_sizes"] = [(layer_features,), (layer_features, layer_features), (layer_features, layer_features // 2)]
config.tune_params["neural_network"]["model__hidden_layer_sizes"] = [(layer_features,), (layer_features, layer_features), (layer_features, layer_features // 2)]
config.tune_params["keras_lstm"]["model__lstm_units_1"] = [16, 32, 64]
pipeline = GeospatialClassificationPipeline(config)

In [8]:
summary_check = pipeline.run_check(df=gdf_parcels)
summary_check

=========================================================
Function <run_check> started on 2026-09-28 15:11:31

Checking input data...

Resetting project output folder: C:\work_dir\neuro_2024-2025a\3_eo_ml_classification_fill
Deleting folder 'C:\work_dir\neuro_2024-2025a\3_eo_ml_classification_fill\01_check'...
Successfully deleted folder 'C:\work_dir\neuro_2024-2025a\3_eo_ml_classification_fill\01_check' on attempt 1
Deleting folder 'C:\work_dir\neuro_2024-2025a\3_eo_ml_classification_fill\02_prepare'...
Successfully deleted folder 'C:\work_dir\neuro_2024-2025a\3_eo_ml_classification_fill\02_prepare' on attempt 1
Deleting folder 'C:\work_dir\neuro_2024-2025a\3_eo_ml_classification_fill\03_train'...
Successfully deleted folder 'C:\work_dir\neuro_2024-2025a\3_eo_ml_classification_fill\03_train' on attempt 1
Deleting folder 'C:\work_dir\neuro_2024-2025a\3_eo_ml_classification_fill\04_evaluate'...
Successfully deleted folder 'C:\work_dir\neuro_2024-2025a\3_eo_ml_classification_fill\04_evaluate' on attempt 1
Deleting folder 'C:\work_dir\neuro_2024-2025a\3_eo_ml_classification_fill\05_predict'...
Successfully deleted folder 'C:\work_dir\neuro_2024-2025a\3_eo_ml_classification_fill\05_predict' on attempt 1
Deleting folder 'C:\work_dir\neuro_2024-2025a\3_eo_ml_classification_fill\final_dashboard'...
Successfully deleted folder 'C:\work_dir\neuro_2024-2025a\3_eo_ml_classification_fill\final_dashboard' on attempt 1

Recreated project output folders under: C:\work_dir\neuro_2024-2025a\3_eo_ml_classification_fill

IQR feature filtering: {'applied': False, 'lower_quantile': 0.25, 'upper_quantile': 0.75, 'multiplier': 1.5, 'outlier_counts': {}, 'total_outliers_replaced': 0, 'bounds': {}, 'skipped_non_numeric_features': ['GAIOIKANOT']}

Feature nulls before spatial interpolation: {'EVI_median__20241201': 1, 'EVI_range__20241201': 1, 'EVI_sd__20241201': 1, 'NDMI_median__20241201': 1, 'NDMI_range__20241201': 1, 'NDMI_sd__20241201': 1, 'NDRE_median__20241201': 1, 'NDRE_range__20241201': 1, 'NDRE_sd__20241201': 1, 'NDVI_median__20241201': 1, 'NDVI_range__20241201': 1, 'NDVI_sd__20241201': 1, 'NDWI_median__20241201': 1, 'NDWI_range__20241201': 1, 'NDWI_sd__20241201': 1, 'SAVI_median__20241201': 1, 'SAVI_range__20241201': 1, 'SAVI_sd__20241201': 1}

Feature nulls after spatial interpolation: {}

Requested features: ['EVI_median__20241001', 'EVI_median__20241101', 'EVI_median__20241201', 'EVI_median__20250101', 'EVI_median__20250201', 'EVI_median__20250301', 'EVI_median__20250401', 'EVI_median__20250501', 'EVI_median__20250601', 'EVI_median__20250701', 'EVI_median__20250801', 'EVI_median__20250901', 'EVI_range__20241001', 'EVI_range__20241101', 'EVI_range__20241201', 'EVI_range__20250101', 'EVI_range__20250201', 'EVI_range__20250301', 'EVI_range__20250401', 'EVI_range__20250501', 'EVI_range__20250601', 'EVI_range__20250701', 'EVI_range__20250801', 'EVI_range__20250901', 'EVI_sd__20241001', 'EVI_sd__20241101', 'EVI_sd__20241201', 'EVI_sd__20250101', 'EVI_sd__20250201', 'EVI_sd__20250301', 'EVI_sd__20250401', 'EVI_sd__20250501', 'EVI_sd__20250601', 'EVI_sd__20250701', 'EVI_sd__20250801', 'EVI_sd__20250901', 'NDMI_median__20241001', 'NDMI_median__20241101', 'NDMI_median__20241201', 'NDMI_median__20250101', 'NDMI_median__20250201', 'NDMI_median__20250301', 'NDMI_median__20250401', 'NDMI_median__20250501', 'NDMI_median__20250601', 'NDMI_median__20250701', 'NDMI_median__20250801', 'NDMI_median__20250901', 'NDMI_range__20241001', 'NDMI_range__20241101', 'NDMI_range__20241201', 'NDMI_range__20250101', 'NDMI_range__20250201', 'NDMI_range__20250301', 'NDMI_range__20250401', 'NDMI_range__20250501', 'NDMI_range__20250601', 'NDMI_range__20250701', 'NDMI_range__20250801', 'NDMI_range__20250901', 'NDMI_sd__20241001', 'NDMI_sd__20241101', 'NDMI_sd__20241201', 'NDMI_sd__20250101', 'NDMI_sd__20250201', 'NDMI_sd__20250301', 'NDMI_sd__20250401', 'NDMI_sd__20250501', 'NDMI_sd__20250601', 'NDMI_sd__20250701', 'NDMI_sd__20250801', 'NDMI_sd__20250901', 'NDRE_median__20241001', 'NDRE_median__20241101', 'NDRE_median__20241201', 'NDRE_median__20250101', 'NDRE_median__20250201', 'NDRE_median__20250301', 'NDRE_median__20250401', 'NDRE_median__20250501', 'NDRE_median__20250601', 'NDRE_median__20250701', 'NDRE_median__20250801', 'NDRE_median__20250901', 'NDRE_range__20241001', 'NDRE_range__20241101', 'NDRE_range__20241201', 'NDRE_range__20250101', 'NDRE_range__20250201', 'NDRE_range__20250301', 'NDRE_range__20250401', 'NDRE_range__20250501', 'NDRE_range__20250601', 'NDRE_range__20250701', 'NDRE_range__20250801', 'NDRE_range__20250901', 'NDRE_sd__20241001', 'NDRE_sd__20241101', 'NDRE_sd__20241201', 'NDRE_sd__20250101', 'NDRE_sd__20250201', 'NDRE_sd__20250301', 'NDRE_sd__20250401', 'NDRE_sd__20250501', 'NDRE_sd__20250601', 'NDRE_sd__20250701', 'NDRE_sd__20250801', 'NDRE_sd__20250901', 'NDVI_median__20241001', 'NDVI_median__20241101', 'NDVI_median__20241201', 'NDVI_median__20250101', 'NDVI_median__20250201', 'NDVI_median__20250301', 'NDVI_median__20250401', 'NDVI_median__20250501', 'NDVI_median__20250601', 'NDVI_median__20250701', 'NDVI_median__20250801', 'NDVI_median__20250901', 'NDVI_range__20241001', 'NDVI_range__20241101', 'NDVI_range__20241201', 'NDVI_range__20250101', 'NDVI_range__20250201', 'NDVI_range__20250301', 'NDVI_range__20250401', 'NDVI_range__20250501', 'NDVI_range__20250601', 'NDVI_range__20250701', 'NDVI_range__20250801', 'NDVI_range__20250901', 'NDVI_sd__20241001', 'NDVI_sd__20241101', 'NDVI_sd__20241201', 'NDVI_sd__20250101', 'NDVI_sd__20250201', 'NDVI_sd__20250301', 'NDVI_sd__20250401', 'NDVI_sd__20250501', 'NDVI_sd__20250601', 'NDVI_sd__20250701', 'NDVI_sd__20250801', 'NDVI_sd__20250901', 'NDWI_median__20241001', 'NDWI_median__20241101', 'NDWI_median__20241201', 'NDWI_median__20250101', 'NDWI_median__20250201', 'NDWI_median__20250301', 'NDWI_median__20250401', 'NDWI_median__20250501', 'NDWI_median__20250601', 'NDWI_median__20250701', 'NDWI_median__20250801', 'NDWI_median__20250901', 'NDWI_range__20241001', 'NDWI_range__20241101', 'NDWI_range__20241201', 'NDWI_range__20250101', 'NDWI_range__20250201', 'NDWI_range__20250301', 'NDWI_range__20250401', 'NDWI_range__20250501', 'NDWI_range__20250601', 'NDWI_range__20250701', 'NDWI_range__20250801', 'NDWI_range__20250901', 'NDWI_sd__20241001', 'NDWI_sd__20241101', 'NDWI_sd__20241201', 'NDWI_sd__20250101', 'NDWI_sd__20250201', 'NDWI_sd__20250301', 'NDWI_sd__20250401', 'NDWI_sd__20250501', 'NDWI_sd__20250601', 'NDWI_sd__20250701', 'NDWI_sd__20250801', 'NDWI_sd__20250901', 'SAVI_median__20241001', 'SAVI_median__20241101', 'SAVI_median__20241201', 'SAVI_median__20250101', 'SAVI_median__20250201', 'SAVI_median__20250301', 'SAVI_median__20250401', 'SAVI_median__20250501', 'SAVI_median__20250601', 'SAVI_median__20250701', 'SAVI_median__20250801', 'SAVI_median__20250901', 'SAVI_range__20241001', 'SAVI_range__20241101', 'SAVI_range__20241201', 'SAVI_range__20250101', 'SAVI_range__20250201', 'SAVI_range__20250301', 'SAVI_range__20250401', 'SAVI_range__20250501', 'SAVI_range__20250601', 'SAVI_range__20250701', 'SAVI_range__20250801', 'SAVI_range__20250901', 'SAVI_sd__20241001', 'SAVI_sd__20241101', 'SAVI_sd__20241201', 'SAVI_sd__20250101', 'SAVI_sd__20250201', 'SAVI_sd__20250301', 'SAVI_sd__20250401', 'SAVI_sd__20250501', 'SAVI_sd__20250601', 'SAVI_sd__20250701', 'SAVI_sd__20250801', 'SAVI_sd__20250901', 'elevation_mean_m', 'GAIOIKANOT', 'x', 'y']
Writing file: C:/work_dir/neuro_2024-2025a/3_eo_ml_classification_fill/01_check/feature_profile.csv

Checked 1150 rows with 220 active features.

Execution time of function <run_check> ended on 2026-09-28 15:11:33 - duration: 00:00:01
==============================================================================================

{'rows_total': 1150,
 'rows_labeled': 1150,
 'rows_unknown_target': 0,
 'n_features_requested': 220,
 'n_features_active': 220,
 'numeric_features': ['EVI_median__20241001',
  'EVI_median__20241101',
  'EVI_median__20241201',
  'EVI_median__20250101',
  'EVI_median__20250201',
  'EVI_median__20250301',
  'EVI_median__20250401',
  'EVI_median__20250501',
  'EVI_median__20250601',
  'EVI_median__20250701',
  'EVI_median__20250801',
  'EVI_median__20250901',
  'EVI_range__20241001',
  'EVI_range__20241101',
  'EVI_range__20241201',
  'EVI_range__20250101',
  'EVI_range__20250201',
  'EVI_range__20250301',
  'EVI_range__20250401',
  'EVI_range__20250501',
  'EVI_range__20250601',
  'EVI_range__20250701',
  'EVI_range__20250801',
  'EVI_range__20250901',
  'EVI_sd__20241001',
  'EVI_sd__20241101',
  'EVI_sd__20241201',
  'EVI_sd__20250101',
  'EVI_sd__20250201',
  'EVI_sd__20250301',
  'EVI_sd__20250401',
  'EVI_sd__20250501',
  'EVI_sd__20250601',
  'EVI_sd__20250701',
  'EVI_sd__20250801',
  'EVI_sd__20250901',
  'NDMI_median__20241001',
  'NDMI_median__20241101',
  'NDMI_median__20241201',
  'NDMI_median__20250101',
  'NDMI_median__20250201',
  'NDMI_median__20250301',
  'NDMI_median__20250401',
  'NDMI_median__20250501',
  'NDMI_median__20250601',
  'NDMI_median__20250701',
  'NDMI_median__20250801',
  'NDMI_median__20250901',
  'NDMI_range__20241001',
  'NDMI_range__20241101',
  'NDMI_range__20241201',
  'NDMI_range__20250101',
  'NDMI_range__20250201',
  'NDMI_range__20250301',
  'NDMI_range__20250401',
  'NDMI_range__20250501',
  'NDMI_range__20250601',
  'NDMI_range__20250701',
  'NDMI_range__20250801',
  'NDMI_range__20250901',
  'NDMI_sd__20241001',
  'NDMI_sd__20241101',
  'NDMI_sd__20241201',
  'NDMI_sd__20250101',
  'NDMI_sd__20250201',
  'NDMI_sd__20250301',
  'NDMI_sd__20250401',
  'NDMI_sd__20250501',
  'NDMI_sd__20250601',
  'NDMI_sd__20250701',
  'NDMI_sd__20250801',
  'NDMI_sd__20250901',
  'NDRE_median__20241001',
  'NDRE_median__20241101',
  'NDRE_median__20241201',
  'NDRE_median__20250101',
  'NDRE_median__20250201',
  'NDRE_median__20250301',
  'NDRE_median__20250401',
  'NDRE_median__20250501',
  'NDRE_median__20250601',
  'NDRE_median__20250701',
  'NDRE_median__20250801',
  'NDRE_median__20250901',
  'NDRE_range__20241001',
  'NDRE_range__20241101',
  'NDRE_range__20241201',
  'NDRE_range__20250101',
  'NDRE_range__20250201',
  'NDRE_range__20250301',
  'NDRE_range__20250401',
  'NDRE_range__20250501',
  'NDRE_range__20250601',
  'NDRE_range__20250701',
  'NDRE_range__20250801',
  'NDRE_range__20250901',
  'NDRE_sd__20241001',
  'NDRE_sd__20241101',
  'NDRE_sd__20241201',
  'NDRE_sd__20250101',
  'NDRE_sd__20250201',
  'NDRE_sd__20250301',
  'NDRE_sd__20250401',
  'NDRE_sd__20250501',
  'NDRE_sd__20250601',
  'NDRE_sd__20250701',
  'NDRE_sd__20250801',
  'NDRE_sd__20250901',
  'NDVI_median__20241001',
  'NDVI_median__20241101',
  'NDVI_median__20241201',
  'NDVI_median__20250101',
  'NDVI_median__20250201',
  'NDVI_median__20250301',
  'NDVI_median__20250401',
  'NDVI_median__20250501',
  'NDVI_median__20250601',
  'NDVI_median__20250701',
  'NDVI_median__20250801',
  'NDVI_median__20250901',
  'NDVI_range__20241001',
  'NDVI_range__20241101',
  'NDVI_range__20241201',
  'NDVI_range__20250101',
  'NDVI_range__20250201',
  'NDVI_range__20250301',
  'NDVI_range__20250401',
  'NDVI_range__20250501',
  'NDVI_range__20250601',
  'NDVI_range__20250701',
  'NDVI_range__20250801',
  'NDVI_range__20250901',
  'NDVI_sd__20241001',
  'NDVI_sd__20241101',
  'NDVI_sd__20241201',
  'NDVI_sd__20250101',
  'NDVI_sd__20250201',
  'NDVI_sd__20250301',
  'NDVI_sd__20250401',
  'NDVI_sd__20250501',
  'NDVI_sd__20250601',
  'NDVI_sd__20250701',
  'NDVI_sd__20250801',
  'NDVI_sd__20250901',
  'NDWI_median__20241001',
  'NDWI_median__20241101',
  'NDWI_median__20241201',
  'NDWI_median__20250101',
  'NDWI_median__20250201',
  'NDWI_median__20250301',
  'NDWI_median__20250401',
  'NDWI_median__20250501',
  'NDWI_median__20250601',
  'NDWI_median__20250701',
  'NDWI_median__20250801',
  'NDWI_median__20250901',
  'NDWI_range__20241001',
  'NDWI_range__20241101',
  'NDWI_range__20241201',
  'NDWI_range__20250101',
  'NDWI_range__20250201',
  'NDWI_range__20250301',
  'NDWI_range__20250401',
  'NDWI_range__20250501',
  'NDWI_range__20250601',
  'NDWI_range__20250701',
  'NDWI_range__20250801',
  'NDWI_range__20250901',
  'NDWI_sd__20241001',
  'NDWI_sd__20241101',
  'NDWI_sd__20241201',
  'NDWI_sd__20250101',
  'NDWI_sd__20250201',
  'NDWI_sd__20250301',
  'NDWI_sd__20250401',
  'NDWI_sd__20250501',
  'NDWI_sd__20250601',
  'NDWI_sd__20250701',
  'NDWI_sd__20250801',
  'NDWI_sd__20250901',
  'SAVI_median__20241001',
  'SAVI_median__20241101',
  'SAVI_median__20241201',
  'SAVI_median__20250101',
  'SAVI_median__20250201',
  'SAVI_median__20250301',
  'SAVI_median__20250401',
  'SAVI_median__20250501',
  'SAVI_median__20250601',
  'SAVI_median__20250701',
  'SAVI_median__20250801',
  'SAVI_median__20250901',
  'SAVI_range__20241001',
  'SAVI_range__20241101',
  'SAVI_range__20241201',
  'SAVI_range__20250101',
  'SAVI_range__20250201',
  'SAVI_range__20250301',
  'SAVI_range__20250401',
  'SAVI_range__20250501',
  'SAVI_range__20250601',
  'SAVI_range__20250701',
  'SAVI_range__20250801',
  'SAVI_range__20250901',
  'SAVI_sd__20241001',
  'SAVI_sd__20241101',
  'SAVI_sd__20241201',
  'SAVI_sd__20250101',
  'SAVI_sd__20250201',
  'SAVI_sd__20250301',
  'SAVI_sd__20250401',
  'SAVI_sd__20250501',
  'SAVI_sd__20250601',
  'SAVI_sd__20250701',
  'SAVI_sd__20250801',
  'SAVI_sd__20250901',
  'elevation_mean_m',
  'x',
  'y'],
 'categorical_features': ['GAIOIKANOT'],
 'all_null_features': [],
 'constant_features': [],
 'active_features': ['EVI_median__20241001',
  'EVI_median__20241101',
  'EVI_median__20241201',
  'EVI_median__20250101',
  'EVI_median__20250201',
  'EVI_median__20250301',
  'EVI_median__20250401',
  'EVI_median__20250501',
  'EVI_median__20250601',
  'EVI_median__20250701',
  'EVI_median__20250801',
  'EVI_median__20250901',
  'EVI_range__20241001',
  'EVI_range__20241101',
  'EVI_range__20241201',
  'EVI_range__20250101',
  'EVI_range__20250201',
  'EVI_range__20250301',
  'EVI_range__20250401',
  'EVI_range__20250501',
  'EVI_range__20250601',
  'EVI_range__20250701',
  'EVI_range__20250801',
  'EVI_range__20250901',
  'EVI_sd__20241001',
  'EVI_sd__20241101',
  'EVI_sd__20241201',
  'EVI_sd__20250101',
  'EVI_sd__20250201',
  'EVI_sd__20250301',
  'EVI_sd__20250401',
  'EVI_sd__20250501',
  'EVI_sd__20250601',
  'EVI_sd__20250701',
  'EVI_sd__20250801',
  'EVI_sd__20250901',
  'NDMI_median__20241001',
  'NDMI_median__20241101',
  'NDMI_median__20241201',
  'NDMI_median__20250101',
  'NDMI_median__20250201',
  'NDMI_median__20250301',
  'NDMI_median__20250401',
  'NDMI_median__20250501',
  'NDMI_median__20250601',
  'NDMI_median__20250701',
  'NDMI_median__20250801',
  'NDMI_median__20250901',
  'NDMI_range__20241001',
  'NDMI_range__20241101',
  'NDMI_range__20241201',
  'NDMI_range__20250101',
  'NDMI_range__20250201',
  'NDMI_range__20250301',
  'NDMI_range__20250401',
  'NDMI_range__20250501',
  'NDMI_range__20250601',
  'NDMI_range__20250701',
  'NDMI_range__20250801',
  'NDMI_range__20250901',
  'NDMI_sd__20241001',
  'NDMI_sd__20241101',
  'NDMI_sd__20241201',
  'NDMI_sd__20250101',
  'NDMI_sd__20250201',
  'NDMI_sd__20250301',
  'NDMI_sd__20250401',
  'NDMI_sd__20250501',
  'NDMI_sd__20250601',
  'NDMI_sd__20250701',
  'NDMI_sd__20250801',
  'NDMI_sd__20250901',
  'NDRE_median__20241001',
  'NDRE_median__20241101',
  'NDRE_median__20241201',
  'NDRE_median__20250101',
  'NDRE_median__20250201',
  'NDRE_median__20250301',
  'NDRE_median__20250401',
  'NDRE_median__20250501',
  'NDRE_median__20250601',
  'NDRE_median__20250701',
  'NDRE_median__20250801',
  'NDRE_median__20250901',
  'NDRE_range__20241001',
  'NDRE_range__20241101',
  'NDRE_range__20241201',
  'NDRE_range__20250101',
  'NDRE_range__20250201',
  'NDRE_range__20250301',
  'NDRE_range__20250401',
  'NDRE_range__20250501',
  'NDRE_range__20250601',
  'NDRE_range__20250701',
  'NDRE_range__20250801',
  'NDRE_range__20250901',
  'NDRE_sd__20241001',
  'NDRE_sd__20241101',
  'NDRE_sd__20241201',
  'NDRE_sd__20250101',
  'NDRE_sd__20250201',
  'NDRE_sd__20250301',
  'NDRE_sd__20250401',
  'NDRE_sd__20250501',
  'NDRE_sd__20250601',
  'NDRE_sd__20250701',
  'NDRE_sd__20250801',
  'NDRE_sd__20250901',
  'NDVI_median__20241001',
  'NDVI_median__20241101',
  'NDVI_median__20241201',
  'NDVI_median__20250101',
  'NDVI_median__20250201',
  'NDVI_median__20250301',
  'NDVI_median__20250401',
  'NDVI_median__20250501',
  'NDVI_median__20250601',
  'NDVI_median__20250701',
  'NDVI_median__20250801',
  'NDVI_median__20250901',
  'NDVI_range__20241001',
  'NDVI_range__20241101',
  'NDVI_range__20241201',
  'NDVI_range__20250101',
  'NDVI_range__20250201',
  'NDVI_range__20250301',
  'NDVI_range__20250401',
  'NDVI_range__20250501',
  'NDVI_range__20250601',
  'NDVI_range__20250701',
  'NDVI_range__20250801',
  'NDVI_range__20250901',
  'NDVI_sd__20241001',
  'NDVI_sd__20241101',
  'NDVI_sd__20241201',
  'NDVI_sd__20250101',
  'NDVI_sd__20250201',
  'NDVI_sd__20250301',
  'NDVI_sd__20250401',
  'NDVI_sd__20250501',
  'NDVI_sd__20250601',
  'NDVI_sd__20250701',
  'NDVI_sd__20250801',
  'NDVI_sd__20250901',
  'NDWI_median__20241001',
  'NDWI_median__20241101',
  'NDWI_median__20241201',
  'NDWI_median__20250101',
  'NDWI_median__20250201',
  'NDWI_median__20250301',
  'NDWI_median__20250401',
  'NDWI_median__20250501',
  'NDWI_median__20250601',
  'NDWI_median__20250701',
  'NDWI_median__20250801',
  'NDWI_median__20250901',
  'NDWI_range__20241001',
  'NDWI_range__20241101',
  'NDWI_range__20241201',
  'NDWI_range__20250101',
  'NDWI_range__20250201',
  'NDWI_range__20250301',
  'NDWI_range__20250401',
  'NDWI_range__20250501',
  'NDWI_range__20250601',
  'NDWI_range__20250701',
  'NDWI_range__20250801',
  'NDWI_range__20250901',
  'NDWI_sd__20241001',
  'NDWI_sd__20241101',
  'NDWI_sd__20241201',
  'NDWI_sd__20250101',
  'NDWI_sd__20250201',
  'NDWI_sd__20250301',
  'NDWI_sd__20250401',
  'NDWI_sd__20250501',
  'NDWI_sd__20250601',
  'NDWI_sd__20250701',
  'NDWI_sd__20250801',
  'NDWI_sd__20250901',
  'SAVI_median__20241001',
  'SAVI_median__20241101',
  'SAVI_median__20241201',
  'SAVI_median__20250101',
  'SAVI_median__20250201',
  'SAVI_median__20250301',
  'SAVI_median__20250401',
  'SAVI_median__20250501',
  'SAVI_median__20250601',
  'SAVI_median__20250701',
  'SAVI_median__20250801',
  'SAVI_median__20250901',
  'SAVI_range__20241001',
  'SAVI_range__20241101',
  'SAVI_range__20241201',
  'SAVI_range__20250101',
  'SAVI_range__20250201',
  'SAVI_range__20250301',
  'SAVI_range__20250401',
  'SAVI_range__20250501',
  'SAVI_range__20250601',
  'SAVI_range__20250701',
  'SAVI_range__20250801',
  'SAVI_range__20250901',
  'SAVI_sd__20241001',
  'SAVI_sd__20241101',
  'SAVI_sd__20241201',
  'SAVI_sd__20250101',
  'SAVI_sd__20250201',
  'SAVI_sd__20250301',
  'SAVI_sd__20250401',
  'SAVI_sd__20250501',
  'SAVI_sd__20250601',
  'SAVI_sd__20250701',
  'SAVI_sd__20250801',
  'SAVI_sd__20250901',
  'elevation_mean_m',
  'GAIOIKANOT',
  'x',
  'y'],
 'iqr_filter': {'applied': False,
  'lower_quantile': 0.25,
  'upper_quantile': 0.75,
  'multiplier': 1.5,
  'outlier_counts': {},
  'total_outliers_replaced': 0,
  'bounds': {},
  'skipped_non_numeric_features': ['GAIOIKANOT']},
 'spatial_interpolation': {'interpolation_method': 'nearest',
  'null_counts_before_interpolation': {'EVI_median__20241201': 1,
   'EVI_range__20241201': 1,
   'EVI_sd__20241201': 1,
   'NDMI_median__20241201': 1,
   'NDMI_range__20241201': 1,
   'NDMI_sd__20241201': 1,
   'NDRE_median__20241201': 1,
   'NDRE_range__20241201': 1,
   'NDRE_sd__20241201': 1,
   'NDVI_median__20241201': 1,
   'NDVI_range__20241201': 1,
   'NDVI_sd__20241201': 1,
   'NDWI_median__20241201': 1,
   'NDWI_range__20241201': 1,
   'NDWI_sd__20241201': 1,
   'SAVI_median__20241201': 1,
   'SAVI_range__20241201': 1,
   'SAVI_sd__20241201': 1},
  'null_cells_before_interpolation': 18,
  'interpolation_skipped': {},
  'null_counts_after_interpolation': {},
  'null_cells_after_interpolation': 0},
 'class_distribution': {'ΚΤΗΝΟΤΡΟΦΙΚΑ ΦΥΤΑ': 305,
  'ΒΑΜΒΑΚΙ': 224,
  'ΣΚΛΗΡΟΣ ΣΙΤΟΣ': 149,
  'ΔΑΣΙΚΑ ΔΕΝΤΡΑ': 95,
  'ΕΝΕΡΓΕΙΑΚΕΣ ΚΑΛΛΙΕΡΓΕΙΕΣ': 82,
  'ΒΟΣΚΟΤΟΠΟΣ': 61,
  'ΛΟΙΠΑ ΣΙΤΗΡΑ': 50,
  'ΑΡΩΜΑΤΙΚΑ ΦΥΤΑ': 49,
  'ΑΓΡΑΝΑΠΑΥΣΗ': 41,
  'ΕΛΑΙΩΝΕΣ': 26,
  'ΓΗ ΠΟΥ ΔΕΝ ΕΝΤΑΣΣΕΤΑΙ ΣΕ ΚΑΛΛΙΕΡΓΗΤΙΚΗ ΔΡΑΣΤΗΡΙΟΤΗΤΑ': 13,
  'ΑΜΠΕΛΩΝΕΣ': 11,
  'ΑΚΡΟΔΡΥΑ (ΚΑΡΠΟΙ ΜΕ ΚΕΛΥΦΟΣ)': 9,
  'ΑΡΑΒΟΣΙΤΟΣ': 8,
  'ΟΣΠΡΙΑ ΒΡΩΣΙΜΑ': 7,
  'ΠΟΡΤΟΚΑΛΙΑ ΠΡΟΣ ΧΥΜΟΠΟΙΗΣΗ': 5,
  'ΠΥΡΗΝΟΚΑΡΠΑ': 5,
  'KHPEYTIKA': 5,
  'ΕΛΑΙΟΥΧΟΙ ΣΠΟΡΟΙ': 5},
 'config': {'project_dir': WindowsPath('C:/work_dir/neuro_2024-2025a/3_eo_ml_classification_fill'),
  'target_column': 'crop_category',
  'feature_columns': ['EVI_median__20241001',
   'EVI_median__20241101',
   'EVI_median__20241201',
   'EVI_median__20250101',
   'EVI_median__20250201',
   'EVI_median__20250301',
   'EVI_median__20250401',
   'EVI_median__20250501',
   'EVI_median__20250601',
   'EVI_median__20250701',
   'EVI_median__20250801',
   'EVI_median__20250901',
   'EVI_range__20241001',
   'EVI_range__20241101',
   'EVI_range__20241201',
   'EVI_range__20250101',
   'EVI_range__20250201',
   'EVI_range__20250301',
   'EVI_range__20250401',
   'EVI_range__20250501',
   'EVI_range__20250601',
   'EVI_range__20250701',
   'EVI_range__20250801',
   'EVI_range__20250901',
   'EVI_sd__20241001',
   'EVI_sd__20241101',
   'EVI_sd__20241201',
   'EVI_sd__20250101',
   'EVI_sd__20250201',
   'EVI_sd__20250301',
   'EVI_sd__20250401',
   'EVI_sd__20250501',
   'EVI_sd__20250601',
   'EVI_sd__20250701',
   'EVI_sd__20250801',
   'EVI_sd__20250901',
   'NDMI_median__20241001',
   'NDMI_median__20241101',
   'NDMI_median__20241201',
   'NDMI_median__20250101',
   'NDMI_median__20250201',
   'NDMI_median__20250301',
   'NDMI_median__20250401',
   'NDMI_median__20250501',
   'NDMI_median__20250601',
   'NDMI_median__20250701',
   'NDMI_median__20250801',
   'NDMI_median__20250901',
   'NDMI_range__20241001',
   'NDMI_range__20241101',
   'NDMI_range__20241201',
   'NDMI_range__20250101',
   'NDMI_range__20250201',
   'NDMI_range__20250301',
   'NDMI_range__20250401',
   'NDMI_range__20250501',
   'NDMI_range__20250601',
   'NDMI_range__20250701',
   'NDMI_range__20250801',
   'NDMI_range__20250901',
   'NDMI_sd__20241001',
   'NDMI_sd__20241101',
   'NDMI_sd__20241201',
   'NDMI_sd__20250101',
   'NDMI_sd__20250201',
   'NDMI_sd__20250301',
   'NDMI_sd__20250401',
   'NDMI_sd__20250501',
   'NDMI_sd__20250601',
   'NDMI_sd__20250701',
   'NDMI_sd__20250801',
   'NDMI_sd__20250901',
   'NDRE_median__20241001',
   'NDRE_median__20241101',
   'NDRE_median__20241201',
   'NDRE_median__20250101',
   'NDRE_median__20250201',
   'NDRE_median__20250301',
   'NDRE_median__20250401',
   'NDRE_median__20250501',
   'NDRE_median__20250601',
   'NDRE_median__20250701',
   'NDRE_median__20250801',
   'NDRE_median__20250901',
   'NDRE_range__20241001',
   'NDRE_range__20241101',
   'NDRE_range__20241201',
   'NDRE_range__20250101',
   'NDRE_range__20250201',
   'NDRE_range__20250301',
   'NDRE_range__20250401',
   'NDRE_range__20250501',
   'NDRE_range__20250601',
   'NDRE_range__20250701',
   'NDRE_range__20250801',
   'NDRE_range__20250901',
   'NDRE_sd__20241001',
   'NDRE_sd__20241101',
   'NDRE_sd__20241201',
   'NDRE_sd__20250101',
   'NDRE_sd__20250201',
   'NDRE_sd__20250301',
   'NDRE_sd__20250401',
   'NDRE_sd__20250501',
   'NDRE_sd__20250601',
   'NDRE_sd__20250701',
   'NDRE_sd__20250801',
   'NDRE_sd__20250901',
   'NDVI_median__20241001',
   'NDVI_median__20241101',
   'NDVI_median__20241201',
   'NDVI_median__20250101',
   'NDVI_median__20250201',
   'NDVI_median__20250301',
   'NDVI_median__20250401',
   'NDVI_median__20250501',
   'NDVI_median__20250601',
   'NDVI_median__20250701',
   'NDVI_median__20250801',
   'NDVI_median__20250901',
   'NDVI_range__20241001',
   'NDVI_range__20241101',
   'NDVI_range__20241201',
   'NDVI_range__20250101',
   'NDVI_range__20250201',
   'NDVI_range__20250301',
   'NDVI_range__20250401',
   'NDVI_range__20250501',
   'NDVI_range__20250601',
   'NDVI_range__20250701',
   'NDVI_range__20250801',
   'NDVI_range__20250901',
   'NDVI_sd__20241001',
   'NDVI_sd__20241101',
   'NDVI_sd__20241201',
   'NDVI_sd__20250101',
   'NDVI_sd__20250201',
   'NDVI_sd__20250301',
   'NDVI_sd__20250401',
   'NDVI_sd__20250501',
   'NDVI_sd__20250601',
   'NDVI_sd__20250701',
   'NDVI_sd__20250801',
   'NDVI_sd__20250901',
   'NDWI_median__20241001',
   'NDWI_median__20241101',
   'NDWI_median__20241201',
   'NDWI_median__20250101',
   'NDWI_median__20250201',
   'NDWI_median__20250301',
   'NDWI_median__20250401',
   'NDWI_median__20250501',
   'NDWI_median__20250601',
   'NDWI_median__20250701',
   'NDWI_median__20250801',
   'NDWI_median__20250901',
   'NDWI_range__20241001',
   'NDWI_range__20241101',
   'NDWI_range__20241201',
   'NDWI_range__20250101',
   'NDWI_range__20250201',
   'NDWI_range__20250301',
   'NDWI_range__20250401',
   'NDWI_range__20250501',
   'NDWI_range__20250601',
   'NDWI_range__20250701',
   'NDWI_range__20250801',
   'NDWI_range__20250901',
   'NDWI_sd__20241001',
   'NDWI_sd__20241101',
   'NDWI_sd__20241201',
   'NDWI_sd__20250101',
   'NDWI_sd__20250201',
   'NDWI_sd__20250301',
   'NDWI_sd__20250401',
   'NDWI_sd__20250501',
   'NDWI_sd__20250601',
   'NDWI_sd__20250701',
   'NDWI_sd__20250801',
   'NDWI_sd__20250901',
   'SAVI_median__20241001',
   'SAVI_median__20241101',
   'SAVI_median__20241201',
   'SAVI_median__20250101',
   'SAVI_median__20250201',
   'SAVI_median__20250301',
   'SAVI_median__20250401',
   'SAVI_median__20250501',
   'SAVI_median__20250601',
   'SAVI_median__20250701',
   'SAVI_median__20250801',
   'SAVI_median__20250901',
   'SAVI_range__20241001',
   'SAVI_range__20241101',
   'SAVI_range__20241201',
   'SAVI_range__20250101',
   'SAVI_range__20250201',
   'SAVI_range__20250301',
   'SAVI_range__20250401',
   'SAVI_range__20250501',
   'SAVI_range__20250601',
   'SAVI_range__20250701',
   'SAVI_range__20250801',
   'SAVI_range__20250901',
   'SAVI_sd__20241001',
   'SAVI_sd__20241101',
   'SAVI_sd__20241201',
   'SAVI_sd__20250101',
   'SAVI_sd__20250201',
   'SAVI_sd__20250301',
   'SAVI_sd__20250401',
   'SAVI_sd__20250501',
   'SAVI_sd__20250601',
   'SAVI_sd__20250701',
   'SAVI_sd__20250801',
   'SAVI_sd__20250901',
   'elevation_mean_m',
   'GAIOIKANOT',
   'x',
   'y'],
  'id_column': 'parcel_id',
  'reset_project_dir_on_run_check': True,
  'fail_on_cleanup_error': False,
  'force_retrain_models': False,
  'apply_iqr': False,
  'iqr_lower_quantile': 0.25,
  'iqr_upper_quantile': 0.75,
  'iqr_multiplier': 1.5,
  'enforce_unique_ids': True,
  'spatial_interpolation_method': 'nearest',
  'spatial_interpolation_max_distance_in_meters': None,
  'spatial_interpolation_variogram_lags': 15,
  'spatial_interpolation_variogram_max_distance_in_meters': None,
  'test_size': 0.2,
  'cv_folds': 5,
  'random_state': 42,
  'spatial_split': True,
  'spatial_split_method': 'by_row',
  'spatial_split_grid_size': 30,
  'selected_models': ('bagging',
   'bayesian',
   'decision_tree',
   'extra_trees',
   'random_forest',
   'gradient_boosting',
   'lightgbm',
   'xgboost',
   'support_vector_machine',
   'knn',
   'neural_network'),
  'max_search_candidates': 40,
  'n_jobs': -1,
  'tune_params': {'logistic_regression': {'model__C': [0.001,
     0.005,
     0.01,
     0.05,
     0.1,
     0.5,
     1.0],
    'model__solver': ['liblinear'],
    'model__penalty': ['l1', 'l2']},
   'linear_sgd_classifier': {'model__alpha': [0.0001, 0.001, 0.01, 0.1],
    'model__l1_ratio': [0.0, 0.15, 0.5, 0.8, 1.0]},
   'support_vector_machine': {'model__C': [0.1, 1.0, 10.0, 20.0],
    'model__kernel': ['linear', 'rbf', 'poly'],
    'model__gamma': ['scale', 'auto'],

In [9]:
summary_prepare = pipeline.run_prepare()
summary_prepare

===========================================================
Function <run_prepare> started on 2026-09-28 15:11:33

Preparing data...

c:\ProgramData\anaconda3\envs\axhub_spatial\Lib\site-packages\sklearn\model_selection\_split.py:1036: UserWarning: The least populated class in y has only 4 members, which is less than n_splits=5.
  warnings.warn(

Writing file: C:/work_dir/neuro_2024-2025a/3_eo_ml_classification_fill/02_prepare/label_mapping.csv

Prepared train/test split: 920 train rows, 230 test rows.

Execution time of function <run_prepare> ended on 2026-09-28 15:11:35 - duration: 00:00:02
================================================================================================

{'active_features': ['EVI_median__20241001',
  'EVI_median__20241101',
  'EVI_median__20241201',
  'EVI_median__20250101',
  'EVI_median__20250201',
  'EVI_median__20250301',
  'EVI_median__20250401',
  'EVI_median__20250501',
  'EVI_median__20250601',
  'EVI_median__20250701',
  'EVI_median__20250801',
  'EVI_median__20250901',
  'EVI_range__20241001',
  'EVI_range__20241101',
  'EVI_range__20241201',
  'EVI_range__20250101',
  'EVI_range__20250201',
  'EVI_range__20250301',
  'EVI_range__20250401',
  'EVI_range__20250501',
  'EVI_range__20250601',
  'EVI_range__20250701',
  'EVI_range__20250801',
  'EVI_range__20250901',
  'EVI_sd__20241001',
  'EVI_sd__20241101',
  'EVI_sd__20241201',
  'EVI_sd__20250101',
  'EVI_sd__20250201',
  'EVI_sd__20250301',
  'EVI_sd__20250401',
  'EVI_sd__20250501',
  'EVI_sd__20250601',
  'EVI_sd__20250701',
  'EVI_sd__20250801',
  'EVI_sd__20250901',
  'NDMI_median__20241001',
  'NDMI_median__20241101',
  'NDMI_median__20241201',
  'NDMI_median__20250101',
  'NDMI_median__20250201',
  'NDMI_median__20250301',
  'NDMI_median__20250401',
  'NDMI_median__20250501',
  'NDMI_median__20250601',
  'NDMI_median__20250701',
  'NDMI_median__20250801',
  'NDMI_median__20250901',
  'NDMI_range__20241001',
  'NDMI_range__20241101',
  'NDMI_range__20241201',
  'NDMI_range__20250101',
  'NDMI_range__20250201',
  'NDMI_range__20250301',
  'NDMI_range__20250401',
  'NDMI_range__20250501',
  'NDMI_range__20250601',
  'NDMI_range__20250701',
  'NDMI_range__20250801',
  'NDMI_range__20250901',
  'NDMI_sd__20241001',
  'NDMI_sd__20241101',
  'NDMI_sd__20241201',
  'NDMI_sd__20250101',
  'NDMI_sd__20250201',
  'NDMI_sd__20250301',
  'NDMI_sd__20250401',
  'NDMI_sd__20250501',
  'NDMI_sd__20250601',
  'NDMI_sd__20250701',
  'NDMI_sd__20250801',
  'NDMI_sd__20250901',
  'NDRE_median__20241001',
  'NDRE_median__20241101',
  'NDRE_median__20241201',
  'NDRE_median__20250101',
  'NDRE_median__20250201',
  'NDRE_median__20250301',
  'NDRE_median__20250401',
  'NDRE_median__20250501',
  'NDRE_median__20250601',
  'NDRE_median__20250701',
  'NDRE_median__20250801',
  'NDRE_median__20250901',
  'NDRE_range__20241001',
  'NDRE_range__20241101',
  'NDRE_range__20241201',
  'NDRE_range__20250101',
  'NDRE_range__20250201',
  'NDRE_range__20250301',
  'NDRE_range__20250401',
  'NDRE_range__20250501',
  'NDRE_range__20250601',
  'NDRE_range__20250701',
  'NDRE_range__20250801',
  'NDRE_range__20250901',
  'NDRE_sd__20241001',
  'NDRE_sd__20241101',
  'NDRE_sd__20241201',
  'NDRE_sd__20250101',
  'NDRE_sd__20250201',
  'NDRE_sd__20250301',
  'NDRE_sd__20250401',
  'NDRE_sd__20250501',
  'NDRE_sd__20250601',
  'NDRE_sd__20250701',
  'NDRE_sd__20250801',
  'NDRE_sd__20250901',
  'NDVI_median__20241001',
  'NDVI_median__20241101',
  'NDVI_median__20241201',
  'NDVI_median__20250101',
  'NDVI_median__20250201',
  'NDVI_median__20250301',
  'NDVI_median__20250401',
  'NDVI_median__20250501',
  'NDVI_median__20250601',
  'NDVI_median__20250701',
  'NDVI_median__20250801',
  'NDVI_median__20250901',
  'NDVI_range__20241001',
  'NDVI_range__20241101',
  'NDVI_range__20241201',
  'NDVI_range__20250101',
  'NDVI_range__20250201',
  'NDVI_range__20250301',
  'NDVI_range__20250401',
  'NDVI_range__20250501',
  'NDVI_range__20250601',
  'NDVI_range__20250701',
  'NDVI_range__20250801',
  'NDVI_range__20250901',
  'NDVI_sd__20241001',
  'NDVI_sd__20241101',
  'NDVI_sd__20241201',
  'NDVI_sd__20250101',
  'NDVI_sd__20250201',
  'NDVI_sd__20250301',
  'NDVI_sd__20250401',
  'NDVI_sd__20250501',
  'NDVI_sd__20250601',
  'NDVI_sd__20250701',
  'NDVI_sd__20250801',
  'NDVI_sd__20250901',
  'NDWI_median__20241001',
  'NDWI_median__20241101',
  'NDWI_median__20241201',
  'NDWI_median__20250101',
  'NDWI_median__20250201',
  'NDWI_median__20250301',
  'NDWI_median__20250401',
  'NDWI_median__20250501',
  'NDWI_median__20250601',
  'NDWI_median__20250701',
  'NDWI_median__20250801',
  'NDWI_median__20250901',
  'NDWI_range__20241001',
  'NDWI_range__20241101',
  'NDWI_range__20241201',
  'NDWI_range__20250101',
  'NDWI_range__20250201',
  'NDWI_range__20250301',
  'NDWI_range__20250401',
  'NDWI_range__20250501',
  'NDWI_range__20250601',
  'NDWI_range__20250701',
  'NDWI_range__20250801',
  'NDWI_range__20250901',
  'NDWI_sd__20241001',
  'NDWI_sd__20241101',
  'NDWI_sd__20241201',
  'NDWI_sd__20250101',
  'NDWI_sd__20250201',
  'NDWI_sd__20250301',
  'NDWI_sd__20250401',
  'NDWI_sd__20250501',
  'NDWI_sd__20250601',
  'NDWI_sd__20250701',
  'NDWI_sd__20250801',
  'NDWI_sd__20250901',
  'SAVI_median__20241001',
  'SAVI_median__20241101',
  'SAVI_median__20241201',
  'SAVI_median__20250101',
  'SAVI_median__20250201',
  'SAVI_median__20250301',
  'SAVI_median__20250401',
  'SAVI_median__20250501',
  'SAVI_median__20250601',
  'SAVI_median__20250701',
  'SAVI_median__20250801',
  'SAVI_median__20250901',
  'SAVI_range__20241001',
  'SAVI_range__20241101',
  'SAVI_range__20241201',
  'SAVI_range__20250101',
  'SAVI_range__20250201',
  'SAVI_range__20250301',
  'SAVI_range__20250401',
  'SAVI_range__20250501',
  'SAVI_range__20250601',
  'SAVI_range__20250701',
  'SAVI_range__20250801',
  'SAVI_range__20250901',
  'SAVI_sd__20241001',
  'SAVI_sd__20241101',
  'SAVI_sd__20241201',
  'SAVI_sd__20250101',
  'SAVI_sd__20250201',
  'SAVI_sd__20250301',
  'SAVI_sd__20250401',
  'SAVI_sd__20250501',
  'SAVI_sd__20250601',
  'SAVI_sd__20250701',
  'SAVI_sd__20250801',
  'SAVI_sd__20250901',
  'elevation_mean_m',
  'GAIOIKANOT',
  'x',
  'y'],
 'train_rows': 920,
 'test_rows': 230,
 'split_strategy': 'spatial_by_row',
 'target_labels': ['KHPEYTIKA',
  'ΑΓΡΑΝΑΠΑΥΣΗ',
  'ΑΚΡΟΔΡΥΑ (ΚΑΡΠΟΙ ΜΕ ΚΕΛΥΦΟΣ)',
  'ΑΜΠΕΛΩΝΕΣ',
  'ΑΡΑΒΟΣΙΤΟΣ',
  'ΑΡΩΜΑΤΙΚΑ ΦΥΤΑ',
  'ΒΑΜΒΑΚΙ',
  'ΒΟΣΚΟΤΟΠΟΣ',
  'ΓΗ ΠΟΥ ΔΕΝ ΕΝΤΑΣΣΕΤΑΙ ΣΕ ΚΑΛΛΙΕΡΓΗΤΙΚΗ ΔΡΑΣΤΗΡΙΟΤΗΤΑ',
  'ΔΑΣΙΚΑ ΔΕΝΤΡΑ',
  'ΕΛΑΙΟΥΧΟΙ ΣΠΟΡΟΙ',
  'ΕΛΑΙΩΝΕΣ',
  'ΕΝΕΡΓΕΙΑΚΕΣ ΚΑΛΛΙΕΡΓΕΙΕΣ',
  'ΚΤΗΝΟΤΡΟΦΙΚΑ ΦΥΤΑ',
  'ΛΟΙΠΑ ΣΙΤΗΡΑ',
  'ΟΣΠΡΙΑ ΒΡΩΣΙΜΑ',
  'ΠΟΡΤΟΚΑΛΙΑ ΠΡΟΣ ΧΥΜΟΠΟΙΗΣΗ',
  'ΠΥΡΗΝΟΚΑΡΠΑ',
  'ΣΚΛΗΡΟΣ ΣΙΤΟΣ'],
 'cv_folds': [{'fold': 0,
   'train_index': [0,
    1,
    4,
    5,
    8,
    9,
    10,
    11,
    12,
    14,
    15,
    17,
    18,
    19,
    20,
    22,
    23,
    24,
    27,
    28,
    29,
    31,
    32,
    33,
    34,
    35,
    36,
    38,
    39,
    40,
    41,
    42,
    43,
    44,
    45,
    46,
    47,
    48,
    49,
    50,
    53,
    54,
    55,
    56,
    57,
    58,
    59,
    60,
    61,
    62,
    63,
    64,
    65,
    66,
    67,
    68,
    69,
    71,
    73,
    74,
    75,
    76,
    77,
    78,
    79,
    80,
    81,
    82,
    83,
    85,
    86,
    87,
    88,
    89,
    90,
    92,
    93,
    94,
    95,
    97,
    98,
    99,
    100,
    101,
    102,
    103,
    104,
    107,
    109,
    110,
    111,
    112,
    113,
    114,
    115,
    116,
    118,
    119,
    121,
    122,
    123,
    124,
    125,
    126,
    129,
    132,
    133,
    134,
    135,
    137,
    138,
    139,
    140,
    141,
    142,
    143,
    144,
    145,
    146,
    147,
    148,
    150,
    152,
    153,
    154,
    155,
    156,
    157,
    158,
    159,
    160,
    161,
    162,
    163,
    165,
    166,
    167,
    168,
    170,
    172,
    173,
    174,
    175,
    177,
    178,
    180,
    181,
    182,
    183,
    184,
    185,
    186,
    187,
    188,
    189,
    190,
    191,
    192,
    193,
    194,
    195,
    198,
    200,
    201,
    204,
    206,
    207,
    209,
    210,
    212,
    214,
    215,
    216,
    217,
    218,
    219,
    220,
    221,
    222,
    223,
    224,
    225,
    226,
    227,
    228,
    230,
    231,
    232,
    233,
    235,
    236,
    237,
    240,
    241,
    242,
    243,
    244,
    245,
    246,
    247,
    248,
    249,
    250,
    251,
    252,
    253,
    254,
    256,
    257,
    259,
    260,
    261,
    262,
    263,
    264,
    265,
    266,
    267,
    268,
    270,
    271,
    272,
    274,
    276,
    277,
    278,
    280,
    281,
    282,
    284,
    285,
    287,
    288,
    289,
    290,
    291,
    292,
    293,
    294,
    295,
    296,
    298,
    299,
    301,
    302,
    303,
    304,
    305,
    306,
    307,
    308,
    309,
    310,
    315,
    316,
    317,
    318,
    319,
    320,
    323,
    325,
    326,
    327,
    328,
    329,
    330,
    331,
    332,
    334,
    336,
    338,
    339,
    340,
    341,
    342,
    343,
    344,
    345,
    346,
    347,
    348,
    349,
    350,
    351,
    352,
    353,
    354,
    355,
    357,
    358,
    359,
    360,
    361,
    363,
    364,
    365,
    366,
    367,
    368,
    369,
    370,
    372,
    373,
    374,
    375,
    376,
    377,
    378,
    379,
    380,
    381,
    382,
    385,
    387,
    388,
    389,
    390,
    391,
    392,
    393,
    394,
    395,
    396,
    397,
    400,
    401,
    402,
    403,
    405,
    406,
    407,
    410,
    412,
    413,
    414,
    415,
    416,
    417,
    419,
    420,
    421,
    422,
    423,
    424,
    425,
    426,
    427,
    428,
    430,
    433,
    435,
    436,
    437,
    438,
    439,
    441,
    443,
    444,
    445,
    446,
    448,
    449,
    450,
    451,
    452,
    453,
    454,
    455,
    456,
    457,
    458,
    459,
    460,
    461,
    463,
    464,
    465,
    467,
    470,
    471,
    474,
    475,
    476,
    478,
    481,
    482,
    483,
    484,
    486,
    487,
    488,
    489,
    490,
    491,
    492,
    493,
    494,
    495,
    496,
    498,
    499,
    500,
    501,
    502,
    503,
    504,
    505,
    506,
    507,
    509,
    510,
    511,
    513,
    514,
    515,
    516,
    517,
    519,
    520,
    521,
    522,
    523,
    524,
    526,
    527,
    528,
    529,
    532,
    533,
    534,
    535,
    536,
    537,
    538,
    539,
    540,
    541,
    542,
    543,
    545,
    546,
    547,
    549,
    551,
    552,
    553,
    554,
    555,
    556,
    557,
    559,
    560,
    562,
    563,
    565,
    566,
    568,
    569,
    571,
    572,
    573,
    574,
    575,
    576,
    577,
    578,
    579,
    581,
    582,
    583,
    584,
    585,
    588,
    590,
    593,
    596,
    597,
    598,
    599,
    601,
    602,
    604,
    607,
    608,
    609,
    610,
    611,
    612,
    613,
    615,
    616,
    617,
    618,
    619,
    620,
    621,
    622,
    624,
    625,
    627,
    628,
    629,
    630,
    631,
    633,
    634,
    635,
    636,
    637,
    638,
    639,
    640,
    641,
    643,
    645,
    646,
    647,
    650,
    651,
    652,
    653,
    654,
    655,
    656,
    657,
    659,
    661,
    662,
    663,
    664,
    666,
    667,
    668,
    669,
    670,
    671,
    672,
    673,
    674,
    675,
    676,
    677,
    678,
    680,
    681,
    682,
    684,
    685,
    686,
    687,
    688,
    689,
    691,
    692,
    693,
    694,
    695,
    696,
    697,
    698,
    699,
    701,
    702,
    703,
    704,
    706,
    707,
    708,
    710,
    711,
    712,
    713,
    714,
    717,
    719,
    720,
    721,
    723,
    724,
    725,
    726,
    728,
    729,
    730,
    731,
    732,
    733,
    734,
    735,
    736,
    738,
    740,
    742,
    743,
    744,
    745,
    746,
    747,
    750,
    751,
    752,
    754,
    755,
    757,
    758,
    759,
    760,
    761,
    762,
    763,
    764,
    765,
    767,
    768,
    770,
    771,
    772,
    773,
    774,
    775,
    776,
    777,
    779,
    780,
    781,
    782,
    783,
    784,
    785,
    786,
    788,
    789,
    791,
    793,
    795,
    796,
    797,
    798,
    799,
    800,
    801,
    803,
    804,
    805,
    809,
    810,
    812,
    813,
    814,
    815,
    816,
    817,
    819,
    820,
    821,
    824,
    825,
    826,
    827,
    828,
    830,
    831,
    832,
    833,
    834,
    835,
    836,
    837,
    838,
    839,
    841,
    843,
    844,
    845,
    846,
    847,
    848,
    849,
    850,
    852,
    853,
    854,
    855,
    857,
    858,
    859,
    860,
    862,
    863,
    864,
    865,
    866,
    867,
    868,
    869,
    870,
    871,
    872,
    873,
    874,
    875,
    876,
    877,
    879,
    880,
    882,
    884,
    885,
    887,
    889,
    890,
    891,
    892,
    893,
    894,
    896,
    897,
    898,
    899,
    900,
    901,
    902,
    903,
    904,
    905,
    906,
    907,
    908,
    909,
    910,
    911,
    915,
    916,
    917,
    918,
    919],
   'valid_index': [2,
    3,
    6,
    7,
    13,
    16,
    21,
    25,
    26,
    30,
    37,
    51,
    52,
    70,
    72,
    84,
    91,
    96,
    105,
    106,
    108,
    117,
    120,
    127,
    128,
    130,
    131,
    136,
    149,
    151,
    164,
    169,
    171,
    176,
    179,
    196,
    197,
    199,
    202,
    203,
    205,
    208,
    211,
    213,
    229,
    234,
    238,
    239,
    255,
    258,
    269,
    273,
    275,
    279,
    283,
    286,
    297,
    300,
    311,
    312,
    313,
    314,
    321,
    322,
    324,
    333,
    335,
    337,
    356,
    362,
    371,
    383,
    384,
    386,
    398,
    399,
    404,
    408,
    409,
    411,
    418,
    429,
    431,
    432,
    434,
    440,
    442,
    447,
    462,
    466,
    468,
    469,
    472,
    473,
    477,
    479,
    480,
    485,
    497,
    508,
    512,
    518,
    525,
    530,
    531,
    544,
    548,
    550,
    558,
    561,
    564,
    567,
    570,
    580,
    586,
    587,
    589,
    591,
    592,
    594,
    595,
    600,
    603,
    605,
    606,
    614,
    623,
    626,
    632,
    642,
    644,
    648,
    649,
    658,
    660,
    665,
    679,
    683,
    690,
    700,
    705,
    709,
    715,
    716,
    718,
    722,
    727,
    737,
    739,
    741,
    748,
    749,
    753,
    756,
    766,
    769,
    778,
    787,
    790,
    792,
    794,
    802,
    806,
    807,
    808,
    811,
    818,
    822,
    823,
    829,
    840,
    842,
    851,
    856,
    861,
    878,
    881,
    883,
    886,
    888,
    895,
    912,
    913,
    914]},
  {'fold': 1,
   'train_index': [0,
    1,
    2,
    3,
    5,
    6,
    7,
    8,
    9,
    10,
    11,
    12,
    13,
    14,
    15,
    16,
    17,
    18,
    20,
    21,
    22,
    23,
    24,
    25,
    26,
    27,
    28,
    29,
    30,
    31,
    32,
    33,
    34,
    35,
    36,
    37,
    39,
    40,
    44,
    45,
    46,
    47,
    48,
    49,
    50,
    51,
    52,
    54,
    55,
    56,
    57,
    58,
    59,
    60,
    61,
    62,
    63,
    65,
    66,
    67,
    68,
    69,
    70,
    71,
    72,
    73,
    74,
    76,
    77,
    79,
    81,
    82,
    83,
    84,
    86,
    87,
    90,
    91,
    93,
    94,
    95,
    96,
    97,
    98,
    100,
    101,
    102,
    104,
    105,
    106,
    107,
    108,
    109,
    110,
    111,
    112,
    113,
    115,
    116,
    117,
    119,
    120,
    123,
    124,
    125,
    126,
    127,
    128,
    129,
    130,
    131,
    133,
    134,
    135,
    136,
    138,
    139,
    143,
    144,
    148,
    149,
    150,
    151,
    152,
    153,
    154,
    155,
    157,
    158,
    159,
    160,
    161,
    162,
    164,
    167,
    168,
    169,
    170,
    171,
    172,
    175,
    176,
    177,
    178,
    179,
    180,
    181,
    183,
    184,
    185,
    186,
    187,
    188,
    189,
    190,
    192,
    193,
    194,
    195,
    196,
    197,
    198,
    199,
    200,
    202,
    203,
    204,
    205,
    206,
    207,
    208,
    209,
    210,
    211,
    212,
    213,
    215,
    216,
    217,
    218,
    219,
    221,
    222,
    223,
    224,
    226,
    228,
    229,
    231,
    232,
    233,
    234,
    235,
    236,
    237,
    238,
    239,
    241,
    242,
    243,
    244,
    245,
    246,
    247,
    248,
    249,
    250,
    252,
    255,
    257,
    258,
    259,
    260,
    261,
    262,
    263,
    266,
    268,
    269,
    270,
    271,
    273,
    274,
    275,
    276,
    277,
    278,
    279,
    282,
    283,
    284,
    285,
    286,
    287,
    288,
    289,
    290,
    291,
    292,
    294,
    296,
    297,
    298,
    300,
    301,
    302,
    303,
    305,
    306,
    307,
    309,
    310,
    311,
    312,
    313,
    314,
    315,
    316,
    317,
    318,
    321,
    322,
    323,
    324,
    325,
    326,
    327,
    328,
    330,
    331,
    332,
    333,
    334,
    335,
    336,
    337,
    338,
    340,
    341,
    342,
    343,
    344,
    345,
    346,
    350,
    351,
    353,
    354,
    356,
    358,
    359,
    362,
    364,
    365,
    366,
    368,
    369,
    371,
    373,
    374,
    375,
    376,
    378,
    379,
    380,
    382,
    383,
    384,
    385,
    386,
    390,
    392,
    393,
    394,
    395,
    396,
    398,
    399,
    400,
    401,
    402,
    403,
    404,
    405,
    406,
    407,
    408,
    409,
    411,
    413,
    414,
    415,
    416,
    417,
    418,
    419,
    420,
    421,
    422,
    423,
    424,
    425,
    426,
    427,
    428,
    429,
    431,
    432,
    433,
    434,
    435,
    436,
    438,
    439,
    440,
    441,
    442,
    444,
    446,
    447,
    448,
    449,
    450,
    451,
    452,
    453,
    454,
    455,
    456,
    457,
    458,
    459,
    460,
    461,
    462,
    463,
    465,
    466,
    468,
    469,
    470,
    471,
    472,
    473,
    474,
    475,
    476,
    477,
    478,
    479,
    480,
    481,
    482,
    483,
    485,
    488,
    489,
    490,
    491,
    492,
    493,
    495,
    496,
    497,
    498,
    499,
    500,
    501,
    502,
    503,
    504,
    505,
    506,
    507,
    508,
    509,
    510,
    511,
    512,
    514,
    515,
    517,
    518,
    519,
    520,
    521,
    522,
    525,
    526,
    527,
    528,
    530,
    531,
    533,
    534,
    535,
    536,
    537,
    538,
    539,
    541,
    544,
    546,
    548,
    549,
    550,
    551,
    552,
    553,
    555,
    557,
    558,
    559,
    561,
    562,
    564,
    565,
    566,
    567,
    568,
    569,
    570,
    572,
    574,
    575,
    576,
    577,
    578,
    579,
    580,
    582,
    584,
    585,
    586,
    587,
    588,
    589,
    590,
    591,
    592,
    593,
    594,
    595,
    597,
    598,
    600,
    601,
    603,
    604,
    605,
    606,
    607,
    610,
    613,
    614,
    615,
    618,
    620,
    621,
    622,
    623,
    625,
    626,
    627,
    628,
    631,
    632,
    634,
    636,
    637,
    638,
    639,
    640,
    641,
    642,
    643,
    644,
    645,
    646,
    647,
    648,
    649,
    651,
    652,
    653,
    655,
    656,
    657,
    658,
    660,
    661,
    662,
    664,
    665,
    668,
    669,
    670,
    671,
    672,
    673,
    674,
    675,
    676,
    677,
    679,
    680,
    682,
    683,
    684,
    685,
    686,
    687,
    689,
    690,
    691,
    692,
    693,
    696,
    697,
    698,
    699,
    700,
    702,
    703,
    704,
    705,
    706,
    707,
    709,
    710,
    711,
    712,
    715,
    716,
    717,
    718,
    719,
    721,
    722,
    723,
    724,
    725,
    727,
    729,
    731,
    732,
    733,
    735,
    736,
    737,
    738,
    739,
    740,
    741,
    742,
    743,
    744,
    745,
    746,
    747,
    748,
    749,
    750,
    751,
    752,
    753,
    754,
    756,
    757,
    758,
    759,
    760,
    761,
    762,
    763,
    764,
    765,
    766,
    767,
    769,
    770,
    771,
    772,
    775,
    776,
    778,
    779,
    780,
    781,
    783,
    785,
    786,
    787,
    789,
    790,
    792,
    793,
    794,
    795,
    796,
    797,
    799,
    800,
    801,
    802,
    804,

In [10]:
summary_train = pipeline.run_train()
summary_train

=========================================================
Function <run_train> started on 2026-09-28 15:11:35

Training models...
Reading file: C:/work_dir/neuro_2024-2025a/3_eo_ml_classification_fill/02_prepare/label_mapping.csv
____________________________________________________________________________________________________

Training model support_vector_machine

c:\ProgramData\anaconda3\envs\axhub_spatial\Lib\site-packages\sklearn\svm\_base.py:239: FutureWarning: The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`
  warnings.warn(

Writing file: C:/work_dir/neuro_2024-2025a/3_eo_ml_classification_fill/03_train/models/support_vector_machine/cv_results.csv

Saved artifacts for support_vector_machine: model=C:\work_dir\neuro_2024-2025a\3_eo_ml_classification_fill\03_train\models\support_vector_machine\best_model.joblib, cv_results=C:\work_dir\neuro_2024-2025a\3_eo_ml_classification_fill\03_train\models\support_vector_machine\cv_results.csv, plot=C:\work_dir\neuro_2024-2025a\3_eo_ml_classification_fill\03_train\models\support_vector_machine\search_results.png

Model support_vector_machine finished in duration: 00:00:10
____________________________________________________________________________________________________

Training model random_forest
Writing file: C:/work_dir/neuro_2024-2025a/3_eo_ml_classification_fill/03_train/models/random_forest/cv_results.csv

Saved artifacts for random_forest: model=C:\work_dir\neuro_2024-2025a\3_eo_ml_classification_fill\03_train\models\random_forest\best_model.joblib, cv_results=C:\work_dir\neuro_2024-2025a\3_eo_ml_classification_fill\03_train\models\random_forest\cv_results.csv, plot=C:\work_dir\neuro_2024-2025a\3_eo_ml_classification_fill\03_train\models\random_forest\search_results.png

Model random_forest finished in duration: 00:03:57
____________________________________________________________________________________________________

Training model extra_trees
Writing file: C:/work_dir/neuro_2024-2025a/3_eo_ml_classification_fill/03_train/models/extra_trees/cv_results.csv

Saved artifacts for extra_trees: model=C:\work_dir\neuro_2024-2025a\3_eo_ml_classification_fill\03_train\models\extra_trees\best_model.joblib, cv_results=C:\work_dir\neuro_2024-2025a\3_eo_ml_classification_fill\03_train\models\extra_trees\cv_results.csv, plot=C:\work_dir\neuro_2024-2025a\3_eo_ml_classification_fill\03_train\models\extra_trees\search_results.png

Model extra_trees finished in duration: 00:01:02
____________________________________________________________________________________________________

Training model gradient_boosting
Writing file: C:/work_dir/neuro_2024-2025a/3_eo_ml_classification_fill/03_train/models/gradient_boosting/cv_results.csv

Saved artifacts for gradient_boosting: model=C:\work_dir\neuro_2024-2025a\3_eo_ml_classification_fill\03_train\models\gradient_boosting\best_model.joblib, cv_results=C:\work_dir\neuro_2024-2025a\3_eo_ml_classification_fill\03_train\models\gradient_boosting\cv_results.csv, plot=C:\work_dir\neuro_2024-2025a\3_eo_ml_classification_fill\03_train\models\gradient_boosting\search_results.png

Model gradient_boosting finished in duration: 00:12:44
____________________________________________________________________________________________________

Training model decision_tree
Writing file: C:/work_dir/neuro_2024-2025a/3_eo_ml_classification_fill/03_train/models/decision_tree/cv_results.csv

Saved artifacts for decision_tree: model=C:\work_dir\neuro_2024-2025a\3_eo_ml_classification_fill\03_train\models\decision_tree\best_model.joblib, cv_results=C:\work_dir\neuro_2024-2025a\3_eo_ml_classification_fill\03_train\models\decision_tree\cv_results.csv, plot=C:\work_dir\neuro_2024-2025a\3_eo_ml_classification_fill\03_train\models\decision_tree\search_results.png

Model decision_tree finished in duration: 00:00:03
____________________________________________________________________________________________________

Training model knn
Writing file: C:/work_dir/neuro_2024-2025a/3_eo_ml_classification_fill/03_train/models/knn/cv_results.csv

Saved artifacts for knn: model=C:\work_dir\neuro_2024-2025a\3_eo_ml_classification_fill\03_train\models\knn\best_model.joblib, cv_results=C:\work_dir\neuro_2024-2025a\3_eo_ml_classification_fill\03_train\models\knn\cv_results.csv, plot=C:\work_dir\neuro_2024-2025a\3_eo_ml_classification_fill\03_train\models\knn\search_results.png

Model knn finished in duration: 00:00:03
____________________________________________________________________________________________________

Training model neural_network
Writing file: C:/work_dir/neuro_2024-2025a/3_eo_ml_classification_fill/03_train/models/neural_network/cv_results.csv

Saved artifacts for neural_network: model=C:\work_dir\neuro_2024-2025a\3_eo_ml_classification_fill\03_train\models\neural_network\best_model.joblib, cv_results=C:\work_dir\neuro_2024-2025a\3_eo_ml_classification_fill\03_train\models\neural_network\cv_results.csv, plot=C:\work_dir\neuro_2024-2025a\3_eo_ml_classification_fill\03_train\models\neural_network\search_results.png

Model neural_network finished in duration: 00:00:37
____________________________________________________________________________________________________

Training model bagging
Writing file: C:/work_dir/neuro_2024-2025a/3_eo_ml_classification_fill/03_train/models/bagging/cv_results.csv

Saved artifacts for bagging: model=C:\work_dir\neuro_2024-2025a\3_eo_ml_classification_fill\03_train\models\bagging\best_model.joblib, cv_results=C:\work_dir\neuro_2024-2025a\3_eo_ml_classification_fill\03_train\models\bagging\cv_results.csv, plot=C:\work_dir\neuro_2024-2025a\3_eo_ml_classification_fill\03_train\models\bagging\search_results.png

Model bagging finished in duration: 00:01:06
____________________________________________________________________________________________________

Training model bayesian
Writing file: C:/work_dir/neuro_2024-2025a/3_eo_ml_classification_fill/03_train/models/bayesian/cv_results.csv

Saved artifacts for bayesian: model=C:\work_dir\neuro_2024-2025a\3_eo_ml_classification_fill\03_train\models\bayesian\best_model.joblib, cv_results=C:\work_dir\neuro_2024-2025a\3_eo_ml_classification_fill\03_train\models\bayesian\cv_results.csv, plot=C:\work_dir\neuro_2024-2025a\3_eo_ml_classification_fill\03_train\models\bayesian\search_results.png

Model bayesian finished in duration: 00:00:00
____________________________________________________________________________________________________

Training model xgboost
Writing file: C:/work_dir/neuro_2024-2025a/3_eo_ml_classification_fill/03_train/models/xgboost/cv_results.csv

Saved artifacts for xgboost: model=C:\work_dir\neuro_2024-2025a\3_eo_ml_classification_fill\03_train\models\xgboost\best_model.joblib, cv_results=C:\work_dir\neuro_2024-2025a\3_eo_ml_classification_fill\03_train\models\xgboost\cv_results.csv, plot=C:\work_dir\neuro_2024-2025a\3_eo_ml_classification_fill\03_train\models\xgboost\search_results.png

Model xgboost finished in duration: 00:05:29
____________________________________________________________________________________________________

Training model lightgbm
Writing file: C:/work_dir/neuro_2024-2025a/3_eo_ml_classification_fill/03_train/models/lightgbm/cv_results.csv

Saved artifacts for lightgbm: model=C:\work_dir\neuro_2024-2025a\3_eo_ml_classification_fill\03_train\models\lightgbm\best_model.joblib, cv_results=C:\work_dir\neuro_2024-2025a\3_eo_ml_classification_fill\03_train\models\lightgbm\cv_results.csv, plot=C:\work_dir\neuro_2024-2025a\3_eo_ml_classification_fill\03_train\models\lightgbm\search_results.png

Model lightgbm finished in duration: 00:04:06
Writing file: C:/work_dir/neuro_2024-2025a/3_eo_ml_classification_fill/03_train/training_summary.csv
Writing file: C:/work_dir/neuro_2024-2025a/3_eo_ml_classification_fill/03_train/training_failed_models.csv
Writing file: C:/work_dir/neuro_2024-2025a/3_eo_ml_classification_fill/03_train/best_cv_fold_scores.csv

Best CV model: xgboost using score_minus_std=0.1398

Execution time of function <run_train> ended on 2026-09-28 15:40:58 - duration: 00:29:22
==============================================================================================

{'models_trained': ['xgboost',
  'random_forest',
  'bagging',
  'extra_trees',
  'lightgbm',
  'support_vector_machine',
  'gradient_boosting',
  'neural_network',
  'knn',
  'bayesian',
  'decision_tree'],
 'models_failed': [],
 'best_cv_model': 'xgboost',
 'cv_ranking_method': 'score_minus_std'}

In [14]:
summary_evaluate = pipeline.run_evaluate()
summary_evaluate

============================================================
Function <run_evaluate> started on 2026-09-28 16:01:32

Evaluating models...
Reading file: C:/work_dir/neuro_2024-2025a/3_eo_ml_classification_fill/02_prepare/label_mapping.csv
Reading file: C:/work_dir/neuro_2024-2025a/3_eo_ml_classification_fill/03_train/training_summary.csv

c:\ProgramData\anaconda3\envs\axhub_spatial\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning:

Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.

c:\ProgramData\anaconda3\envs\axhub_spatial\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning:

Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.

c:\ProgramData\anaconda3\envs\axhub_spatial\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning:

Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.

Removing existing file: C:/work_dir/neuro_2024-2025a/3_eo_ml_classification_fill/04_evaluate/reports/support_vector_machine_classification_report.csv
Writing file: C:/work_dir/neuro_2024-2025a/3_eo_ml_classification_fill/04_evaluate/reports/support_vector_machine_classification_report.csv

c:\ProgramData\anaconda3\envs\axhub_spatial\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning:

Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.

c:\ProgramData\anaconda3\envs\axhub_spatial\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning:

Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.

c:\ProgramData\anaconda3\envs\axhub_spatial\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning:

Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.

Removing existing file: C:/work_dir/neuro_2024-2025a/3_eo_ml_classification_fill/04_evaluate/reports/random_forest_classification_report.csv
Writing file: C:/work_dir/neuro_2024-2025a/3_eo_ml_classification_fill/04_evaluate/reports/random_forest_classification_report.csv

c:\ProgramData\anaconda3\envs\axhub_spatial\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning:

Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.

c:\ProgramData\anaconda3\envs\axhub_spatial\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning:

Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.

c:\ProgramData\anaconda3\envs\axhub_spatial\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning:

Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.

Removing existing file: C:/work_dir/neuro_2024-2025a/3_eo_ml_classification_fill/04_evaluate/reports/extra_trees_classification_report.csv
Writing file: C:/work_dir/neuro_2024-2025a/3_eo_ml_classification_fill/04_evaluate/reports/extra_trees_classification_report.csv

c:\ProgramData\anaconda3\envs\axhub_spatial\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning:

Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.

c:\ProgramData\anaconda3\envs\axhub_spatial\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning:

Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.

c:\ProgramData\anaconda3\envs\axhub_spatial\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning:

Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.

Removing existing file: C:/work_dir/neuro_2024-2025a/3_eo_ml_classification_fill/04_evaluate/reports/gradient_boosting_classification_report.csv
Writing file: C:/work_dir/neuro_2024-2025a/3_eo_ml_classification_fill/04_evaluate/reports/gradient_boosting_classification_report.csv

c:\ProgramData\anaconda3\envs\axhub_spatial\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning:

Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.

c:\ProgramData\anaconda3\envs\axhub_spatial\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning:

Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.

c:\ProgramData\anaconda3\envs\axhub_spatial\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning:

Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.

Removing existing file: C:/work_dir/neuro_2024-2025a/3_eo_ml_classification_fill/04_evaluate/reports/decision_tree_classification_report.csv
Writing file: C:/work_dir/neuro_2024-2025a/3_eo_ml_classification_fill/04_evaluate/reports/decision_tree_classification_report.csv

c:\ProgramData\anaconda3\envs\axhub_spatial\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning:

Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.

c:\ProgramData\anaconda3\envs\axhub_spatial\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning:

Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.

c:\ProgramData\anaconda3\envs\axhub_spatial\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning:

Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.

Removing existing file: C:/work_dir/neuro_2024-2025a/3_eo_ml_classification_fill/04_evaluate/reports/knn_classification_report.csv
Writing file: C:/work_dir/neuro_2024-2025a/3_eo_ml_classification_fill/04_evaluate/reports/knn_classification_report.csv
Removing existing file: C:/work_dir/neuro_2024-2025a/3_eo_ml_classification_fill/04_evaluate/reports/neural_network_classification_report.csv
Writing file: C:/work_dir/neuro_2024-2025a/3_eo_ml_classification_fill/04_evaluate/reports/neural_network_classification_report.csv

c:\ProgramData\anaconda3\envs\axhub_spatial\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning:

Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.

c:\ProgramData\anaconda3\envs\axhub_spatial\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning:

Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.

c:\ProgramData\anaconda3\envs\axhub_spatial\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning:

Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.

Removing existing file: C:/work_dir/neuro_2024-2025a/3_eo_ml_classification_fill/04_evaluate/reports/bagging_classification_report.csv
Writing file: C:/work_dir/neuro_2024-2025a/3_eo_ml_classification_fill/04_evaluate/reports/bagging_classification_report.csv
Removing existing file: C:/work_dir/neuro_2024-2025a/3_eo_ml_classification_fill/04_evaluate/reports/bayesian_classification_report.csv
Writing file: C:/work_dir/neuro_2024-2025a/3_eo_ml_classification_fill/04_evaluate/reports/bayesian_classification_report.csv

c:\ProgramData\anaconda3\envs\axhub_spatial\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning:

Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.

c:\ProgramData\anaconda3\envs\axhub_spatial\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning:

Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.

c:\ProgramData\anaconda3\envs\axhub_spatial\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning:

Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.

Removing existing file: C:/work_dir/neuro_2024-2025a/3_eo_ml_classification_fill/04_evaluate/reports/xgboost_classification_report.csv
Writing file: C:/work_dir/neuro_2024-2025a/3_eo_ml_classification_fill/04_evaluate/reports/xgboost_classification_report.csv

c:\ProgramData\anaconda3\envs\axhub_spatial\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning:

Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.

c:\ProgramData\anaconda3\envs\axhub_spatial\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning:

Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.

c:\ProgramData\anaconda3\envs\axhub_spatial\Lib\site-packages\sklearn\metrics\_classification.py:1879: UndefinedMetricWarning:

Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.

Removing existing file: C:/work_dir/neuro_2024-2025a/3_eo_ml_classification_fill/04_evaluate/reports/lightgbm_classification_report.csv
Writing file: C:/work_dir/neuro_2024-2025a/3_eo_ml_classification_fill/04_evaluate/reports/lightgbm_classification_report.csv
Removing existing file: C:/work_dir/neuro_2024-2025a/3_eo_ml_classification_fill/04_evaluate/model_metrics_train.csv
Writing file: C:/work_dir/neuro_2024-2025a/3_eo_ml_classification_fill/04_evaluate/model_metrics_train.csv
Removing existing file: C:/work_dir/neuro_2024-2025a/3_eo_ml_classification_fill/04_evaluate/model_metrics_test.csv
Writing file: C:/work_dir/neuro_2024-2025a/3_eo_ml_classification_fill/04_evaluate/model_metrics_test.csv
Removing existing file: C:/work_dir/neuro_2024-2025a/3_eo_ml_classification_fill/04_evaluate/interpretability/xgboost_feature_importance.csv
Writing file: C:/work_dir/neuro_2024-2025a/3_eo_ml_classification_fill/04_evaluate/interpretability/xgboost_feature_importance.csv
Removing existing file: C:/work_dir/neuro_2024-2025a/3_eo_ml_classification_fill/04_evaluate/interpretability/random_forest_feature_importance.csv
Writing file: C:/work_dir/neuro_2024-2025a/3_eo_ml_classification_fill/04_evaluate/interpretability/random_forest_feature_importance.csv
Removing existing file: C:/work_dir/neuro_2024-2025a/3_eo_ml_classification_fill/04_evaluate/interpretability/extra_trees_feature_importance.csv
Writing file: C:/work_dir/neuro_2024-2025a/3_eo_ml_classification_fill/04_evaluate/interpretability/extra_trees_feature_importance.csv
Removing existing file: C:/work_dir/neuro_2024-2025a/3_eo_ml_classification_fill/04_evaluate/interpretability/lightgbm_feature_importance.csv
Writing file: C:/work_dir/neuro_2024-2025a/3_eo_ml_classification_fill/04_evaluate/interpretability/lightgbm_feature_importance.csv
Removing existing file: C:/work_dir/neuro_2024-2025a/3_eo_ml_classification_fill/04_evaluate/interpretability/gradient_boosting_feature_importance.csv
Writing file: C:/work_dir/neuro_2024-2025a/3_eo_ml_classification_fill/04_evaluate/interpretability/gradient_boosting_feature_importance.csv
Removing existing file: C:/work_dir/neuro_2024-2025a/3_eo_ml_classification_fill/04_evaluate/interpretability/interpretability_summary.csv
Writing file: C:/work_dir/neuro_2024-2025a/3_eo_ml_classification_fill/04_evaluate/interpretability/interpretability_summary.csv
Removing existing file: C:/work_dir/neuro_2024-2025a/3_eo_ml_classification_fill/04_evaluate/model_metrics_train_with_voting.csv
Writing file: C:/work_dir/neuro_2024-2025a/3_eo_ml_classification_fill/04_evaluate/model_metrics_train_with_voting.csv
Removing existing file: C:/work_dir/neuro_2024-2025a/3_eo_ml_classification_fill/04_evaluate/model_metrics_test_with_voting.csv
Writing file: C:/work_dir/neuro_2024-2025a/3_eo_ml_classification_fill/04_evaluate/model_metrics_test_with_voting.csv
Removing existing file: C:/work_dir/neuro_2024-2025a/3_eo_ml_classification_fill/04_evaluate/geo_classifier_style_train_metrics.csv
Writing file: C:/work_dir/neuro_2024-2025a/3_eo_ml_classification_fill/04_evaluate/geo_classifier_style_train_metrics.csv
Removing existing file: C:/work_dir/neuro_2024-2025a/3_eo_ml_classification_fill/04_evaluate/geo_classifier_style_test_metrics.csv
Writing file: C:/work_dir/neuro_2024-2025a/3_eo_ml_classification_fill/04_evaluate/geo_classifier_style_test_metrics.csv
Removing existing file: C:/work_dir/neuro_2024-2025a/3_eo_ml_classification_fill/04_evaluate/ranking/parcel_best_class_by_ranking.csv
Writing file: C:/work_dir/neuro_2024-2025a/3_eo_ml_classification_fill/04_evaluate/ranking/parcel_best_class_by_ranking.csv
Removing existing file: C:/work_dir/neuro_2024-2025a/3_eo_ml_classification_fill/04_evaluate/ranking/parcel_best_class_by_ranking_train.csv
Writing file: C:/work_dir/neuro_2024-2025a/3_eo_ml_classification_fill/04_evaluate/ranking/parcel_best_class_by_ranking_train.csv
Removing existing file: C:/work_dir/neuro_2024-2025a/3_eo_ml_classification_fill/04_evaluate/ranking/ranking_method_metrics.csv
Writing file: C:/work_dir/neuro_2024-2025a/3_eo_ml_classification_fill/04_evaluate/ranking/ranking_method_metrics.csv
Removing existing file: C:/work_dir/neuro_2024-2025a/3_eo_ml_classification_fill/04_evaluate/ranking/ranking_method_metrics_train.csv
Writing file: C:/work_dir/neuro_2024-2025a/3_eo_ml_classification_fill/04_evaluate/ranking/ranking_method_metrics_train.csv
Removing existing file: C:/work_dir/neuro_2024-2025a/3_eo_ml_classification_fill/04_evaluate/confidence/class_reliability_oof.csv
Writing file: C:/work_dir/neuro_2024-2025a/3_eo_ml_classification_fill/04_evaluate/confidence/class_reliability_oof.csv
Removing existing file: C:/work_dir/neuro_2024-2025a/3_eo_ml_classification_fill/04_evaluate/confidence/rank_confidence_test.csv
Writing file: C:/work_dir/neuro_2024-2025a/3_eo_ml_classification_fill/04_evaluate/confidence/rank_confidence_test.csv
Removing existing file: C:/work_dir/neuro_2024-2025a/3_eo_ml_classification_fill/04_evaluate/confidence/confidence_level_metrics_test.csv
Writing file: C:/work_dir/neuro_2024-2025a/3_eo_ml_classification_fill/04_evaluate/confidence/confidence_level_metrics_test.csv
Removing existing file: C:/work_dir/neuro_2024-2025a/3_eo_ml_classification_fill/04_evaluate/confidence/confidence_by_class_test.csv
Writing file: C:/work_dir/neuro_2024-2025a/3_eo_ml_classification_fill/04_evaluate/confidence/confidence_by_class_test.csv
Removing existing file: C:/work_dir/neuro_2024-2025a/3_eo_ml_classification_fill/04_evaluate/confidence/rank_confidence_oof.csv
Writing file: C:/work_dir/neuro_2024-2025a/3_eo_ml_classification_fill/04_evaluate/confidence/rank_confidence_oof.csv
Removing existing file: C:/work_dir/neuro_2024-2025a/3_eo_ml_classification_fill/04_evaluate/confidence/confidence_level_metrics_oof.csv
Writing file: C:/work_dir/neuro_2024-2025a/3_eo_ml_classification_fill/04_evaluate/confidence/confidence_level_metrics_oof.csv
Reading file: C:/work_dir/neuro_2024-2025a/3_eo_ml_classification_fill/04_evaluate/interpretability/interpretability_summary.csv
Reading file: C:/work_dir/neuro_2024-2025a/3_eo_ml_classification_fill/04_evaluate/model_metrics_train_with_voting.csv
Reading file: C:/work_dir/neuro_2024-2025a/3_eo_ml_classification_fill/04_evaluate/model_metrics_test_with_voting.csv
Reading file: C:/work_dir/neuro_2024-2025a/3_eo_ml_classification_fill/04_evaluate/interpretability/interpretability_summary.csv
Reading file: C:/work_dir/neuro_2024-2025a/3_eo_ml_classification_fill/03_train/training_summary.csv

Generated final dashboard: C:\work_dir\neuro_2024-2025a\3_eo_ml_classification_fill\final_dashboard\report.html

Selected strategy: soft_voting using ['xgboost', 'random_forest', 'bagging', 'extra_trees', 'lightgbm', 'support_vector_machine', 'gradient_boosting', 'neural_network']

Execution time of function <run_evaluate> ended on 2026-09-28 16:01:48 - duration: 00:00:16
=================================================================================================

{'selection_type': 'soft_voting',
 'selected_models': ['xgboost',
  'random_forest',
  'bagging',
  'extra_trees',
  'lightgbm',
  'support_vector_machine',
  'gradient_boosting',
  'neural_network'],
 'selected_metric': 'cv_score_minus_std',
 'selected_score': 0.12475514546844316,
 'selection_source': 'cross_validation',
 'labels': ['KHPEYTIKA',
  'ΑΓΡΑΝΑΠΑΥΣΗ',
  'ΑΚΡΟΔΡΥΑ (ΚΑΡΠΟΙ ΜΕ ΚΕΛΥΦΟΣ)',
  'ΑΜΠΕΛΩΝΕΣ',
  'ΑΡΑΒΟΣΙΤΟΣ',
  'ΑΡΩΜΑΤΙΚΑ ΦΥΤΑ',
  'ΒΑΜΒΑΚΙ',
  'ΒΟΣΚΟΤΟΠΟΣ',
  'ΓΗ ΠΟΥ ΔΕΝ ΕΝΤΑΣΣΕΤΑΙ ΣΕ ΚΑΛΛΙΕΡΓΗΤΙΚΗ ΔΡΑΣΤΗΡΙΟΤΗΤΑ',
  'ΔΑΣΙΚΑ ΔΕΝΤΡΑ',
  'ΕΛΑΙΟΥΧΟΙ ΣΠΟΡΟΙ',
  'ΕΛΑΙΩΝΕΣ',
  'ΕΝΕΡΓΕΙΑΚΕΣ ΚΑΛΛΙΕΡΓΕΙΕΣ',
  'ΚΤΗΝΟΤΡΟΦΙΚΑ ΦΥΤΑ',
  'ΛΟΙΠΑ ΣΙΤΗΡΑ',
  'ΟΣΠΡΙΑ ΒΡΩΣΙΜΑ',
  'ΠΟΡΤΟΚΑΛΙΑ ΠΡΟΣ ΧΥΜΟΠΟΙΗΣΗ',
  'ΠΥΡΗΝΟΚΑΡΠΑ',
  'ΣΚΛΗΡΟΣ ΣΙΤΟΣ'],
 'class_probability_multipliers': {'KHPEYTIKA': 1.0,
  'ΑΓΡΑΝΑΠΑΥΣΗ': 1.5,
  'ΑΚΡΟΔΡΥΑ (ΚΑΡΠΟΙ ΜΕ ΚΕΛΥΦΟΣ)': 1.2,
  'ΑΜΠΕΛΩΝΕΣ': 1.5,
  'ΑΡΑΒΟΣΙΤΟΣ': 1.0,
  'ΑΡΩΜΑΤΙΚΑ ΦΥΤΑ': 2.0,
  'ΒΑΜΒΑΚΙ': 0.8,
  'ΒΟΣΚΟΤΟΠΟΣ': 0.8,
  'ΓΗ ΠΟΥ ΔΕΝ ΕΝΤΑΣΣΕΤΑΙ ΣΕ ΚΑΛΛΙΕΡΓΗΤΙΚΗ ΔΡΑΣΤΗΡΙΟΤΗΤΑ': 1.2,
  'ΔΑΣΙΚΑ ΔΕΝΤΡΑ': 0.8,
  'ΕΛΑΙΟΥΧΟΙ ΣΠΟΡΟΙ': 0.8,
  'ΕΛΑΙΩΝΕΣ': 0.8,
  'ΕΝΕΡΓΕΙΑΚΕΣ ΚΑΛΛΙΕΡΓΕΙΕΣ': 1.5,
  'ΚΤΗΝΟΤΡΟΦΙΚΑ ΦΥΤΑ': 1.0,
  'ΛΟΙΠΑ ΣΙΤΗΡΑ': 2.0,
  'ΟΣΠΡΙΑ ΒΡΩΣΙΜΑ': 1.0,
  'ΠΟΡΤΟΚΑΛΙΑ ΠΡΟΣ ΧΥΜΟΠΟΙΗΣΗ': 1.0,
  'ΠΥΡΗΝΟΚΑΡΠΑ': 1.0,
  'ΣΚΛΗΡΟΣ ΣΙΤΟΣ': 1.2},
 'probability_optimization': {'baseline_oof_macro_f1': 0.20344480119277095,
  'optimized_oof_macro_f1': 0.2210715306666063,
  'baseline_oof_accuracy': 0.45760869565217394,
  'optimized_oof_accuracy': 0.4532608695652174},
 'confidence': {'enabled': True,
  'method': 'rank_consensus_only',
  'version': '2.0',
  'prediction_basis': 'soft_voting',
  'class_reliability_enabled': False,
  'rank': {'minimum_models': 3,
   'high_min_borda': 90.0,
   'high_max_range': 2.0,
   'medium_min_borda': 75.0,
   'medium_max_range': 4.0},
  'class_reliability': {'method': 'oof_precision',
   'source': 'oof_soft_voting_precision',
   'version': '2.0',
   'minimum_oof_support': 100,
   'high_min_precision': 0.8,
   'medium_min_precision': 0.6,
   'oof_rows_total': 920,
   'classes': {'KHPEYTIKA': {'support': 0,
     'correct': 0,
     'precision': None,
     'level': 'LOW',
     'valid': False,
     'reason': 'insufficient_oof_class_support'},
    'ΑΓΡΑΝΑΠΑΥΣΗ': {'support': 38,
     'correct': 5,
     'precision': 0.13157894736842105,
     'level': 'LOW',
     'valid': False,
     'reason': 'insufficient_oof_class_support'},
    'ΑΚΡΟΔΡΥΑ (ΚΑΡΠΟΙ ΜΕ ΚΕΛΥΦΟΣ)': {'support': 5,
     'correct': 0,
     'precision': 0.0,
     'level': 'LOW',
     'valid': False,
     'reason': 'insufficient_oof_class_support'},
    'ΑΜΠΕΛΩΝΕΣ': {'support': 2,
     'correct': 0,
     'precision': 0.0,
     'level': 'LOW',
     'valid': False,
     'reason': 'insufficient_oof_class_support'},
    'ΑΡΑΒΟΣΙΤΟΣ': {'support': 0,
     'correct': 0,
     'precision': None,
     'level': 'LOW',
     'valid': False,
     'reason': 'insufficient_oof_class_support'},
    'ΑΡΩΜΑΤΙΚΑ ΦΥΤΑ': {'support': 56,
     'correct': 17,
     'precision': 0.30357142857142855,
     'level': 'LOW',
     'valid': False,
     'reason': 'insufficient_oof_class_support'},
    'ΒΑΜΒΑΚΙ': {'support': 118,
     'correct': 46,
     'precision': 0.3898305084745763,
     'level': 'LOW',
     'valid': True,
     'reason': 'precision_below_medium_threshold'},
    'ΒΟΣΚΟΤΟΠΟΣ': {'support': 50,
     'correct': 45,
     'precision': 0.9,
     'level': 'LOW',
     'valid': False,
     'reason': 'insufficient_oof_class_support'},
    'ΓΗ ΠΟΥ ΔΕΝ ΕΝΤΑΣΣΕΤΑΙ ΣΕ ΚΑΛΛΙΕΡΓΗΤΙΚΗ ΔΡΑΣΤΗΡΙΟΤΗΤΑ': {'support': 2,
     'correct': 0,
     'precision': 0.0,
     'level': 'LOW',
     'valid': False,
     'reason': 'insufficient_oof_class_support'},
    'ΔΑΣΙΚΑ ΔΕΝΤΡΑ': {'support': 67,
     'correct': 35,
     'precision': 0.5223880597014925,
     'level': 'LOW',
     'valid': False,
     'reason': 'insufficient_oof_class_support'},
    'ΕΛΑΙΟΥΧΟΙ ΣΠΟΡΟΙ': {'support': 0,
     'correct': 0,
     'precision': None,
     'level': 'LOW',
     'valid': False,
     'reason': 'insufficient_oof_class_support'},
    'ΕΛΑΙΩΝΕΣ': {'support': 31,
     'correct': 6,
     'precision': 0.1935483870967742,
     'level': 'LOW',
     'valid': False,
     'reason': 'insufficient_oof_class_support'},
    'ΕΝΕΡΓΕΙΑΚΕΣ ΚΑΛΛΙΕΡΓΕΙΕΣ': {'support': 98,
     'correct': 46,
     'precision': 0.46938775510204084,
     'level': 'LOW',
     'valid': False,
     'reason': 'insufficient_oof_class_support'},
    'ΚΤΗΝΟΤΡΟΦΙΚΑ ΦΥΤΑ': {'support': 277,
     'correct': 147,
     'precision': 0.5306859205776173,
     'level': 'LOW',
     'valid': True,
     'reason': 'precision_below_medium_threshold'},
    'ΛΟΙΠΑ ΣΙΤΗΡΑ': {'support': 35,
     'correct': 5,
     'precision': 0.14285714285714285,
     'level': 'LOW',
     'valid': False,
     'reason': 'insufficient_oof_class_support'},
    'ΟΣΠΡΙΑ ΒΡΩΣΙΜΑ': {'support': 1,
     'correct': 0,
     'precision': 0.0,
     'level': 'LOW',
     'valid': False,
     'reason': 'insufficient_oof_class_support'},
    'ΠΟΡΤΟΚΑΛΙΑ ΠΡΟΣ ΧΥΜΟΠΟΙΗΣΗ': {'support': 1,
     'correct': 0,
     'precision': 0.0,
     'level': 'LOW',
     'valid': False,
     'reason': 'insufficient_oof_class_support'},
    'ΠΥΡΗΝΟΚΑΡΠΑ': {'support': 0,
     'correct': 0,
     'precision': None,
     'level': 'LOW',
     'valid': False,
     'reason': 'insufficient_oof_class_support'},
    'ΣΚΛΗΡΟΣ ΣΙΤΟΣ': {'support': 139,
     'correct': 65,
     'precision': 0.4676258992805755,
     'level': 'LOW',
     'valid': True,
     'reason': 'precision_below_medium_threshold'}}},
  'holdout_accuracy_monotonic': False,
  'holdout_level_counts': {'HIGH': 175, 'LOW': 45, 'MEDIUM': 10},
  'holdout_rank_level_counts': {'HIGH': 175, 'LOW': 45, 'MEDIUM': 10},
  'holdout_class_reliability_level_counts': {'LOW': 230},
  'oof_level_counts': {'HIGH': 563, 'LOW': 291, 'MEDIUM': 66},
  'oof_rank_level_counts': {'HIGH': 563, 'LOW': 291, 'MEDIUM': 66},
  'oof_class_reliability_level_counts': {'LOW': 920}},
 'rank_confidence': {'enabled': True,
  'method': 'rank_consensus_only',
  'version': '2.0',
  'prediction_basis': 'soft_voting',
  'class_reliability_enabled': False,
  'rank': {'minimum_models': 3,
   'high_min_borda': 90.0,
   'high_max_range': 2.0,
   'medium_min_borda': 75.0,
   'medium_max_range': 4.0},
  'class_reliability': {'method': 'oof_precision',
   'source': 'oof_soft_voting_precision',
   'version': '2.0',
   'minimum_oof_support': 100,
   'high_min_precision': 0.8,
   'medium_min_precision': 0.6,
   'oof_rows_total': 920,
   'classes': {'KHPEYTIKA': {'support': 0,
     'correct': 0,
     'precision': None,
     'level': 'LOW',
     'valid': False,
     'reason': 'insufficient_oof_class_support'},
    'ΑΓΡΑΝΑΠΑΥΣΗ': {'support': 38,
     'correct': 5,
     'precision': 0.13157894736842105,
     'level': 'LOW',
     'valid': False,
     'reason': 'insufficient_oof_class_support'},
    'ΑΚΡΟΔΡΥΑ (ΚΑΡΠΟΙ ΜΕ ΚΕΛΥΦΟΣ)': {'support': 5,
     'correct': 0,
     'precision': 0.0,
     'level': 'LOW',
     'valid': False,
     'reason': 'insufficient_oof_class_support'},
    'ΑΜΠΕΛΩΝΕΣ': {'support': 2,
     'correct': 0,
     'precision': 0.0,
     'level': 'LOW',
     'valid': False,
     'reason': 'insufficient_oof_class_support'},
    'ΑΡΑΒΟΣΙΤΟΣ': {'support': 0,
     'correct': 0,
     'precision': None,
     'level': 'LOW',
     'valid': False,
     'reason': 'insufficient_oof_class_support'},
    'ΑΡΩΜΑΤΙΚΑ ΦΥΤΑ': {'support': 56,
     'correct': 17,
     'precision': 0.30357142857142855,
     'level': 'LOW',
     'valid': False,
     'reason': 'insufficient_oof_class_support'},
    'ΒΑΜΒΑΚΙ': {'support': 118,
     'correct': 46,
     'precision': 0.3898305084745763,
     'level': 'LOW',
     'valid': True,
     'reason': 'precision_below_medium_threshold'},
    'ΒΟΣΚΟΤΟΠΟΣ': {'support': 50,
     'correct': 45,
     'precision': 0.9,
     'level': 'LOW',
     'valid': False,
     'reason': 'insufficient_oof_class_support'},
    'ΓΗ ΠΟΥ ΔΕΝ ΕΝΤΑΣΣΕΤΑΙ ΣΕ ΚΑΛΛΙΕΡΓΗΤΙΚΗ ΔΡΑΣΤΗΡΙΟΤΗΤΑ': {'support': 2,
     'correct': 0,
     'precision': 0.0,
     'level': 'LOW',
     'valid': False,
     'reason': 'insufficient_oof_class_support'},
    'ΔΑΣΙΚΑ ΔΕΝΤΡΑ': {'support': 67,
     'correct': 35,
     'precision': 0.5223880597014925,
     'level': 'LOW',
     'valid': False,
     'reason': 'insufficient_oof_class_support'},
    'ΕΛΑΙΟΥΧΟΙ ΣΠΟΡΟΙ': {'support': 0,
     'correct': 0,
     'precision': None,
     'level': 'LOW',
     'valid': False,
     'reason': 'insufficient_oof_class_support'},
    'ΕΛΑΙΩΝΕΣ': {'support': 31,
     'correct': 6,
     'precision': 0.1935483870967742,
     'level': 'LOW',
     'valid': False,
     'reason': 'insufficient_oof_class_support'},
    'ΕΝΕΡΓΕΙΑΚΕΣ ΚΑΛΛΙΕΡΓΕΙΕΣ': {'support': 98,
     'correct': 46,
     'precision': 0.46938775510204084,
     'level': 'LOW',
     'valid': False,
     'reason': 'insufficient_oof_class_support'},
    'ΚΤΗΝΟΤΡΟΦΙΚΑ ΦΥΤΑ': {'support': 277,
     'correct': 147,
     'precision': 0.5306859205776173,
     'level': 'LOW',
     'valid': True,
     'reason': 'precision_below_medium_threshold'},
    'ΛΟΙΠΑ ΣΙΤΗΡΑ': {'support': 35,
     'correct': 5,
     'precision': 0.14285714285714285,
     'level': 'LOW',
     'valid': False,
     'reason': 'insufficient_oof_class_support'},
    'ΟΣΠΡΙΑ ΒΡΩΣΙΜΑ': {'support': 1,
     'correct': 0,
     'precision': 0.0,
     'level': 'LOW',
     'valid': False,
     'reason': 'insufficient_oof_class_support'},
    'ΠΟΡΤΟΚΑΛΙΑ ΠΡΟΣ ΧΥΜΟΠΟΙΗΣΗ': {'support': 1,
     'correct': 0,
     'precision': 0.0,
     'level': 'LOW',
     'valid': False,
     'reason': 'insufficient_oof_class_support'},
    'ΠΥΡΗΝΟΚΑΡΠΑ': {'support': 0,
     'correct': 0,
     'precision': None,
     'level': 'LOW',
     'valid': False,
     'reason': 'insufficient_oof_class_support'},
    'ΣΚΛΗΡΟΣ ΣΙΤΟΣ': {'support': 139,
     'correct': 65,
     'precision': 0.4676258992805755,
     'level': 'LOW',
     'valid': True,
     'reason': 'precision_below_medium_threshold'}}},
  'holdout_accuracy_monotonic': False,
  'holdout_level_counts': {'HIGH': 175, 'LOW': 45, 'MEDIUM': 10},
  'holdout_rank_level_counts': {'HIGH': 175, 'LOW': 45, 'MEDIUM': 10},
  'holdout_class_reliability_level_counts': {'LOW': 230},
  'oof_level_counts': {'HIGH': 563, 'LOW': 291, 'MEDIUM': 66},
  'oof_rank_level_counts': {'HIGH': 563, 'LOW': 291, 'MEDIUM': 66},
  'oof_class_reliability_level_counts': {'LOW': 920}},
 '_schema': {'artifact': 'selection_summary', 'schema_version': '1.2.0'}}

In [15]:
summary_predict = pipeline.run_predict()
summary_predict

===========================================================
Function <run_predict> started on 2026-09-28 16:01:48

Classify all data...
Reading file: C:/work_dir/neuro_2024-2025a/3_eo_ml_classification_fill/02_prepare/label_mapping.csv

c:\ProgramData\anaconda3\envs\axhub_spatial\Lib\site-packages\sklearn\svm\_base.py:239: FutureWarning:

The `probability` parameter was deprecated in 1.9 and will be removed in version 1.11. Use `CalibratedClassifierCV(SVC(), ensemble=False)` instead of `SVC(probability=True)`

Removing existing file: C:/work_dir/neuro_2024-2025a/3_eo_ml_classification_fill/05_predict/final_predictions_preview.csv
Writing file: C:/work_dir/neuro_2024-2025a/3_eo_ml_classification_fill/05_predict/final_predictions_preview.csv

Filled 0 unknown labels.

Execution time of function <run_predict> ended on 2026-09-28 16:03:33 - duration: 00:01:44
================================================================================================

{'selection_type': 'soft_voting',
 'selected_models': ['xgboost',
  'random_forest',
  'bagging',
  'extra_trees',
  'lightgbm',
  'support_vector_machine',
  'gradient_boosting',
  'neural_network'],
 'rows_filled': 0,
 'rows_unknown_original': 0,
 'rows_needing_review': 57,
 'prediction_max_probability_column': 'prediction_max_probability',
 'review_decision_basis': 'rank_confidence',
 'rank_confidence_enabled': True,
 'rank_confidence_contract_source': 'selection_summary',
 'confidence_method': 'rank_consensus_only',
 'class_reliability_enabled': False,
 'class_reliability_applied_to_final_confidence': False,
 'class_reliability_method': 'oof_precision',
 'final_confidence_rule': 'rank_only',
 'rank_confidence_minimum_models': 3,
 'rank_confidence_level_counts': {'HIGH': 1070, 'LOW': 57, 'MEDIUM': 23},
 'output_path': 'C:\\work_dir\\neuro_2024-2025a\\3_eo_ml_classification_fill\\05_predict\\final_predictions.joblib',
 'inspection_scoring_enabled': True,
 'inspection_scoring_available': True,
 'inspection_weights': {'model': 0.6, 'data': 0.25, 'geometry': 0.15},
 'inspection_need_counts': {'MEDIUM': 988,
  'LOW': 97,
  'MEDIUM_HIGH': 55,
  'HIGH': 7,
  'VERY_HIGH': 3},
 'inspection_check_type_counts': {'INSUFFICIENT_EO_EVIDENCE': 1043,
  'NONE': 97,
  'DECLARATION_CONFLICT': 10},
 'label_prediction_status_counts': {'SAME': 1085, 'DIFFERENT': 65},
 'inspection_score_mean': 18.339565217391304,
 '_schema': {'artifact': 'predict_summary', 'schema_version': '1.2.0'}}